### ISSUE TITLE
Presse-Introtext aktualisieren

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#101]

**Comment by lucypatterson** [comment]
Small changes: https://docs.google.com/document/d/1M0Q6eFl9mEJOEfQFlB_ShBv55Y9YMmCIMrjab1Lwe8s/edit#heading=h.swlzl4905kp5

@Lars2i could you please doublecheck my "German", thx

**Comment by Lars2i** [comment]
done

**Comment by anjadigis** [comment]
@fischerdata @lucypatterson - bleibt der "Titel" als Koordinatorin bei BF? (nur zur info für mich - will nicht diskutieren...) - und sollte nicht noch Lucy als Ansprechpartnerin auftauchen?

**Comment by fischerdata** [comment]
eigentlich fände ich es gut, wenn wir eine email adresse info@codingdavinci.de hätten. Ansonsten wäre ich dafür, dass wir es einheitlich machen: Barbara Fischer Projektleitung (siehe auch Koopvertrag) ; Lucy Patterson Projektmanagement. Im Footer sollte dies auch geändert werden.

**Comment by anjadigis** [comment]
@fischerdata @lucypatterson die gibt es, sobald ihr die kennungen abholt :)

**Comment by lucypatterson** [comment]
Requesting Freigabe#1 from @fischerdata: https://docs.google.com/document/d/1M0Q6eFl9mEJOEfQFlB_ShBv55Y9YMmCIMrjab1Lwe8s/edit#

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting Freigabe#2 from the rest of the GT.
Thanks!

**Comment by gitstief** [comment]
~Gründerveto - Von mir gibt's keine Freigabe - da müssen wir noch 1-2 Runden drehen.~
UPDATE 2017-04-12, 16:50 Uhr: Ich habe mich auf das GoogleDoc in #66 bezogen.

**Comment by fischerdata** [comment]
hi Stephan, kannst Du bitte spezifizieren, was du genau geändert haben möchtest. Andernfalls bliebe diese Seite unverändert.

**Comment by gitstief** [comment]
~Ich habe im Googledoc kommentiert. Das sollte als Input reichen.~
UPDATE 2017-04-12, 16:50 Uhr: Ich habe mich auf das GoogleDoc in #66 bezogen.

**Comment by lucypatterson** [comment]
I think this @gitstief's comment landed on the wrong ticket - I'm assuming he's talking about #66 here (Landing page CdV intro). The Presse text looks, at least for the timebeing, good (further changes to be made in the next round).

Requesting Freigabe#2 from @gitstief & @anjadigis: https://docs.google.com/document/d/1M0Q6eFl9mEJOEfQFlB_ShBv55Y9YMmCIMrjab1Lwe8s/edit#

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before passing to Marlen.
Thanks!

**Comment by gitstief** [comment]
You're completely right @lucypatterson ! So sorry for that, everybody!

The only request for change I have is the "-koordination" vs. "-leitung" issue. @fischerdata : You lobbied for exactly that change since the very beginning and must be happy to finally being able to implement it. I for one think it's a badge of honour, being a "Projektkoordinator" for the DDB competence network myself.

**Comment by nosy79** [comment]
Ich hab es eingebaut. Kann es so online gehen?

**Comment by lucypatterson** [comment]
Hi @nosy79,
A couple of typos in the first sentence. It should read, "Wir freuen uns über Ihre Presseanfragen und stellen Ihnen gern weitere Informationen zu **Coding da Vinci Berlin 2017** und auch **Coding da Vinci Nord 2016** zur Verfügung."
Thanks
Lucy

**Comment by nosy79** [comment]
Found 2 errors in the year numbers - should be fixed.

**Comment by lucypatterson** [comment]
Here's the link to the Vorschau: https://codingdavinci.de:8080/presse/
Requesting Freigabe from @fischerdata.

Please notify us in a comment when you have finished reviewing.
Thanks!

**Comment by fischerdata** [comment]
Freigabe erfolgt.

**Comment by lucypatterson** [comment]
Freigabe! @nosy79 - please merge :)

**Comment by fischerdata** [comment]
Bitte ergänzen: Informationen zu Coding da Vinci 2017 und auch Coding da Vinci Nord 2016 zur Verfügung. >> Informationen zu Coding da Vinci 2017 und auch zu Coding da Vinci Nord 2016 zur Verfügung.
