### ISSUE TITLE
englischen Text aktualisieren

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#104]

**Comment by lucypatterson** [comment]
Here: https://codingdavinci.de/english-infos/
See comment gitstief: https://github.com/codingdavinci/codingdavinci.de/issues/67#issuecomment-291845477

**Comment by lucypatterson** [comment]
Requesting Freigabe#1 from @fischerdata for a new draft of the English CdV DNA text: https://docs.google.com/document/d/1xbEzJ9deGYaT69iqvgu3tUTtwsDohjpNigsvEWWmSSM/edit#

I hope it's along the right lines!
Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting Freigabe#2 from the rest of the GT.
Lars will also translate from this to make the German version.
Thanks!

**Comment by fischerdata** [comment]
Freigabe unter Berücksichtigung der kleinen Korrekturen erfolgt. Danke

**Comment by lucypatterson** [comment]
Requesting Freigabe#2 from @gitstief & @anjadigis: https://docs.google.com/document/d/1xbEzJ9deGYaT69iqvgu3tUTtwsDohjpNigsvEWWmSSM/edit#

Please notify me in a comment when you have finished reviewing. I will check and incorporate edits, Lars will finish translating, and we will pass both texts on to Marlen.
Thanks!

**Comment by anjadigis** [comment]
@lucypatterson ein Änderungsvorschlag unter "Welche Ziele verfolgt Coding da Vinci?" - you can adopt ist, but you don't have to. Ansonsten OK.

**Comment by lucypatterson** [comment]
Hi @nosy79 
I've isolated the English parts here: https://docs.google.com/document/d/118fPVudrybBcHYZQKhe6OhRBz8DJdUM9YOFL7zPdbCU/edit#
Please note - I removed one of the original images.
Please go ahead and implement in dev branch here https://codingdavinci.de/english-infos/ - I assume we can restructure the navigation afterwards.

Thanks!

**Comment by fischerdata** [comment]
hi lucy I am online as you can see. I will go through the Vorschau now & hopefully Freigabe immediately or at least before I get to HH. wim bfisch

**Comment by fischerdata** [comment]
ammendment: runs for a total of 6 weeks >> runs for a total of at least 6 weeks

**Comment by fischerdata** [comment]
delete: The 6-week sprint begins >> The sprint begins

**Comment by fischerdata** [comment]
delete: Over the next 6 weeks >> Over the next  weeks

**Comment by fischerdata** [comment]
delete: be copied without cost, if they can be >> be copied, if they can be

**Comment by fischerdata** [comment]
delete: the the visitor >> the visitor

**Comment by fischerdata** [comment]
delete commata: museums, and libraries >> museums and libraries

**Comment by fischerdata** [comment]
add link: The Coding da Vinci project archive is >> The [Coding da Vinci project archive] is

**Comment by fischerdata** [comment]
english translation: doppelgänger >> doppelganger

**Comment by fischerdata** [comment]
spelling: hi-tech insect box >> high-tech insect box

**Comment by fischerdata** [comment]
spelling: Coding da VInci >> Coding da Vinci

**Comment by fischerdata** [comment]
spelling / delete: of the Salomon Ludwig Steinheim-Institut für deutsch-jüdische Geschichte made either >> of the Salomon-Ludwig-Steinheim-Institut für deutsch-jüdische Geschichte made or >> of the Steinheim-Institut für deutsch-jüdische Geschichte made

**Comment by fischerdata** [comment]
no new paragraph: t was to collaborate with a young, interdisciplinary team, who looked at archival images with fresh eyes.
Impressed with the concepts they came up with and how much they were able to create in a short time, for her it also highlighted the kind technological >>
t was to collaborate with a young, interdisciplinary team, who looked at archival images with fresh eyes. Impressed with the concepts they came up with and how much they were able to create in a short time, for her it also highlighted the kind technological

**Comment by fischerdata** [comment]
translation: Gemeinschaftsprojekt to community project sounds doubtful to me. The idea in German is we aka the 4 institutions do it together, the way I understand the English version: it is a community project as Wikipedia. But I am not the native speaker.
For the rest THANKS a lot for this very nice intro. Freigabe is given.  wim bfisch

**Comment by lucypatterson** [comment]
Hi @nosy79 - I've summarised all Barbara's comments and corrections, together with a couple of my own, in the google doc: https://docs.google.com/document/d/118fPVudrybBcHYZQKhe6OhRBz8DJdUM9YOFL7zPdbCU/edit# - hopefully that makes it easier to track everything. Thanks!

**Comment by nosy79** [comment]
Lets give Freigabe another chance. :)

**Comment by lucypatterson** [comment]
I'm not seeing any changes yet........

**Comment by nosy79** [comment]
I just commited them. Please reload again.

**Comment by lucypatterson** [comment]
cool.. there are still a couple of minor corrections outstanding in the google doc (it's getting late..!), and I was wondering - you added new hyperlink that links to the :8080 Vorschau version of the page - will that automatically update with merge?? (I've commented it in the google doc)

**Comment by nosy79** [comment]
ok when it gets late i better go to bed and see what i can do tomorrow. I basically try to make relative links as much as I can so on every web instance (mine on the local host, vorschau and production) the internal links should work. you can see it in the code.

**Comment by nosy79** [comment]
added some small changes from lucy. @lucypatterson requesting release.
