### ISSUE TITLE
Abnahme vor dem Onlinestellen

### ISSUE THREAD

**Issue by nosy79** [codingdavinci/codingdavinci.de#108]
Ihr seid ja zu dritt. Ich nehme mal an, eine Menge Änderungen an der Seite werden irgendwann abgenommen werden müssen.
Man könnte sich da zu festen Zeiten verabreden, um die Änderungen geballt online zu stellen.
Ich hab mich grade gefragt, ob ihr das dann alle drei abnehmen wollt oder nur einer oder so, eine Regel, die von euch kommt, fänd ich ganz schön.
Sowas wie "wenns nur was kleines ist, reicht, wenn es ein Gründer freigibt" - dann müsste ich wissen, was "was kleines" ist usw.
Oder: das allerletzte Go gibt Barbara oder oder oder...

**Comment by nosy79** [comment]
1. Freigabe Barbara, 2. Freigabe Gründungsteam
schnelle kurze Freigaben: nur Barbara

**Comment by gitstief** [comment]
Ja, klar: Kleinigkeiten gerne direkt von @fischerdata abnehmen lassen, das kan Barbara auch selbst entscheiden. Größeres kann man dann ja hoffentlich bald im Staging-System abnehmen.

**Comment by anjadigis** [comment]
Hallo, Abnahme kann gern hauptsächlich auch Barbara machen. Wir werden ja keine brandneuen Texte da haben mit völlig differenten Inhalten. Die großen Strukturänderungen halten sich in Grenzen, glaube ich. @fischerdata - entscheide, wann Du uns hinzuziehst. Melde Dich einfach dazu oder sonst über das staging system.

**Comment by lucypatterson** [comment]
To summarise:
small changes - @fischerdata only
'significant' changes (defined by @fischerdata) - whole Gründungsteam via staging system

Sounds good to me.

**Comment by gitstief** [comment]
@nosy79 Diente dieses Ticket nur der Klärung der Vorgehensweise? Dann könnten wir es schließen.

Oder geht es hier um eine Abnahme (im Staging-System?)?

**Comment by nosy79** [comment]
Es ging nur  um die Vorgehensweise auf organisatorischer Seite.

**Comment by gitstief** [comment]
Das haben wir ja geklärt. Dann mache ich mal zu.
