### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#109]
Identified by Hanna (so far only under the Data section):
https://docs.google.com/document/d/19_UsOuTgMFi6zlfNQ3KidB-lgSOD3WwNhzKLcXegTiM/edit#heading=h.rmn0tdon0jmv

**Comment by lucypatterson** [comment]
Hanna will ask Ralph for help with a link checker to double check whole website

**Comment by gitstief** [comment]
https://validator.w3.org/checklink?uri=https%3A%2F%2Fcodingdavinci.de&hide_type=all&depth=&check=Check

**Comment by nosy79** [comment]
Kaputte links - das * davor steht für unsere Seite:

 http://www.bergervoet-agueras.de/ueber_uns.php - wohin soll das jetzt zeigen?
-> da hin? https://bergervoetproductions.wordpress.com/

*       https://codingdavinci.de/news/2015/07/17/Von-Rodinia-nach-Berlin.html -
error Line: 126 http://knutator2.github.io/Rolling-Stone/
    Status: 404 Not Found


        http://knutator2.github.io/Rolling-Stone/#/ (line 126)
        http://knutator2.github.io/Rolling-Stone/#/graph?stone=481072 (line 126)

error Line: 118 https://creativecommons.org/licenses/by/3.0/Coding%20da%20Vinci
    Status: 404 Not Found




*       https://codingdavinci.de/dokumentation/
error Line: 226 https://commons.wikimedia.org/wiki/Category:Fotos_Kick_Off_25._%26_26.04%0A.2015
    Status: 404 Not Found

error Line: 227 https://commons.wikimedia.org/wiki/Category:Fotos_Preisverleihung_Coding%0A_da_Vinci_05.07.2015

*    https://codingdavinci.de/presse/

error Line: 275 https://archive20.hypotheses.org/3383
    Status: 403 Forbidden

* https://codingdavinci.de/daten/

ine: 4493 https://www.textgrid.de/ueber-textgrid/digitale-bibliothek/
    Status: 302 -> 404 Not Found
Line: 3160 http://www.berlin.de/geschichte/verbannte-buecher/
    Status: 404 Not Found
Line: 1312 http://www.deutsches-museum.de/ausstellungen/musikinstrumente/projekte/notenrollen/
    Status: 404 Not Found
error Line: 6451 http://slks.dk/kulturarv/kulturarvsdatabaser/til-udviklere/hack4dk/
    Status: 404 Not Found
 Line: 2596 http://www.naturkundemuseum-berlin.de/en/sammlungen/palaeontologie/mikropalaeontologie-ehrenberg-sammlung/
    Status: 302 -> 404 Not Found
 Line: 2467 https://offenedaten.de/group/quellensammlung-mpiwg
    Status: 404 Not Found
Line: 5006 http://www.zlb.de/grossstadtgeschichten redirected to https://www.zlb.de/service/digitale-dienste/projekte/grossstadtgeschichten.html
    Status: 301 -> 404 Not Found
 Line: 1983 https://codingdavinci.de/daten/www.mimecentrum.de
    Status: 404 Not Found
Line: 3159 http://daten.berlin.de/datensaetze/liste-der-verbannten-b%C3%BCcher
    Status: 403 Forbidden
Line: 5879 https://github.com/MKGHamburg/SammlungOnlineCodingdaVinci2016
    Status: 404 Not Found
Line: 6186 http://hamburg.gomus.de/production/gomus_coding_da_vinci_mysql.sql redirected to https://hamburg.gomus.de/production/gomus_coding_da_vinci_mysql.sql
    Status: 404 Not Found
 Line: 1410 https://beta.offenedaten.de/dataset/ae56296f-1da8-4c92-baf2-d3ad2857a79a/resource/a2248fbf-e11a-434d-84d3-ea98c6403fe0/download/csv.zip
    Status: 404 Not Found


*https://codingdavinci.de/css/codingdavinci.css
Line: (N/A) https://codingdavinci.de/img/best_design.png
    Status: 404 Not Found



*https://codingdavinci.de/news/2015/07/07/Die-fruchtbare-Dialektik-von-Coding-da-Vinci.html

Line: 131 http://wesuku.de/floradex/www/
    Status: 500 Can't connect to wesuku.de:80


Line: 143 http://imperii-viz.de/
    Status: 500 Can't connect to imperii-viz.de:80



*https://codingdavinci.de/news/2015/08/11/Der-Reiz-von-L%C3%B6chern-und-Streifen.html
https://codingdavinci.de/news/2015/06/17/Von-Rodinia-nach-Berlin.html
    Status: 404 Not Found
http://www.deutsches-museum.de/ausstellungen/musikinstrumente/projekte/notenrollen
    Status: 404 Not Found
https://codingdavinci.de/news/2015/06/07/Die-fruchtbare-Dialektik-von-Coding-da-Vinci.html
    Status: 404 Not Found
error Line: 150 https://git.urgs.org/codingdavinci2015_fu_khb_notenrollen/midiola
    Status: 502 Bad Gateway


*https://codingdavinci.de/projects/2014/verbotene-autoren.html

http://mr-fridge.de/apps/verbotene_autoren/index.php

*https://codingdavinci.de/projects/2014/snatchtheculturegame.html
https://github.com/2P3H8131C1CP4/SnatchTheCultureGame

*https://codingdavinci.de/projects/2014/berlin-50-jahre-spaeter.html
Line: 194 http://cdv.sourcloud.com/berlin

**Comment by nosy79** [comment]
Wo sollen die Links hinzeigen?

**Comment by lucypatterson** [comment]
Hi @nosy79 ,
Please check the google doc linked at the top of this thread, replace broken links wherever there is an alternative, then run the link-checker again so we can see what's left.
Thanks!

**Comment by nosy79** [comment]
Ich hab die Webseite mal bei den Google Webmaster-Tools eingetragen und Ralph nach dem Piwik-Link gefragt. Dort kriegen wir hoffentlich die aktuellen 404er irgendwo raus, sonst gehe ich nocheinmal mit dem Linkchecker drüber.

**Comment by lucypatterson** [comment]
Hi @nosy79 
Any progress? Would be great to see which links are still broken.
Thanks

**Comment by nosy79** [comment]
Hi @lucypatterson,

yes there is. I only have to fix some of the email links which I already can fix but I have a Google Doc to share. Shall  I send it over to Hanna or just you?

**Comment by lucypatterson** [comment]
Would be great if you could share the google doc with me and Hanna, and also link to it here. Thanks!

**Comment by nosy79** [comment]
@lucypatterson thats the link to the broken links doc.
I used a script so I can rerun.

https://docs.google.com/spreadsheets/d/1emnOeJLDiS6eHmudoQPWj2uPqqmMXIDAr9qEM_fNa3c/edit#gid=1484838041
