### ISSUE TITLE
Edits to the Navibar

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#117]
In order to add a new page for the German Coding da Vinci DNA text #67, we need to make some changes in the navibar:

News | Events | Daten | Projekte | Dokumentation | Stimmen | Gründer (vormals "über uns") | Presse | über / about (vormals nur englische Fahne) | twitter (weiterhin nur als Logo)

**To Dos:**
1. Rename "Über uns" to "Gründer" 
2. "über / about" is styled as one tab, but "über" and "about" are separate links. "über" links to #67 and "about" links to https://codingdavinci.de/english-infos/ (#104)

**Comment by nosy79** [comment]
Ich packs mal in die Vorschau :)
