### ISSUE TITLE
codingdavinci.de für Google Webmastertools anmelden

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#129]
Gehört mE für jede Webseite dazu. @nosy79: Magst Du uns dort anmelden?

**Comment by nosy79** [comment]
Ich hab uns mal eingetragen. Weisst du eigentlich wie ich zu den Piwik-Stats komme? Nur über Ralph?

**Comment by nosy79** [comment]
@gitstief ^^

**Comment by nosy79** [comment]
@gitstief: ich hab uns jetzt bei den Google Webmastertools angemeldet und würde dich gern als Nutzer hinzufügen. Wie ist deine Google-Adresse dafür? Die dnb-Adresse wurde nicht akzeptiert.
