### ISSUE TITLE
HTML für codingdavinci.de validieren

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#130]
Zur Zeit gibt http://validator.w3.org/check?uri=https%3A%2F%2Fcodingdavinci.de%2F noch einige Fehler aus.

Bitte fixen.

**Comment by nosy79** [comment]
besser :)

**Comment by gitstief** [comment]
Ja, aber noch nicht vollständig gefixt, 5 Fehler und 1 Warning, die mE schnell behoben sein müssten, bleiben laut [W3C-Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fcodingdavinci.de%2F):

> Error: End tag header seen, but there were open elements.
From line 62, column 6; to line 62, column 14
</a>↩	    </header>↩    ↩
Error: Unclosed element div.
From line 48, column 8; to line 48, column 47
v>↩	      <div class="container header-container">↩↩    
Warning: The navigation role is unnecessary for element nav.
From line 66, column 9; to line 66, column 61
>↩        <nav class="navbar navbar-davinci" role="navigation">↩     
Error: An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.
From line 140, column 6; to line 140, column 63
ge">↩					<img src="/img/news/2017/news-kickoff-berlin-2017.jpeg" />↩				<
Error: The frameborder attribute on the iframe element is obsolete. Use CSS instead.
From line 189, column 13; to line 189, column 140
          <iframe class="widget" width="560" height="315" src="https://www.youtube.com/embed/i6bgXZH9CqY" frameborder="0" allowfullscreen></ifra
Error: No p element in scope but a p end tag seen.
From line 209, column 2; to line 209, column 5
018.</p>↩	</p>↩    <

**Comment by nosy79** [comment]
Die Fixes sind erst in der Vorschau mit drin. Bitte validier mal https://codingdavinci.de:8080.

**Comment by gitstief** [comment]
Cool. Sorry, da hätte ich selbst drauf kommen müssen.
