### ISSUE TITLE
Last fixes for Strukturveränderung

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#133]
Last fixes for Issue #71.

Prio 1 - once these are fixed we will ask for Freigabe from the GT. Deadline asap - please notify me when complete.
- [x] Landing page header banner text "der Kulturhackathon" needs to be returned to its original position inside the logo banner
- [ ] Line between 1st and 2nd level navigation bar should be full-width.
- [x] Text in overview page banners in body for CdV Berlin and CdV Nord should read “Berlin 2017”, “Nord 2017”. The same is true for the banners in the header sections of the respective event pages https://codingdavinci.de:8080/events/berlin/ and https://codingdavinci.de:8080/events/nord - please use the same banners. 

Prio 2
- [ ] Ensure events overview page banners in body for CdV Berlin and CdV Nord maintain same proportions and relative font size & position at different screen widths
- [x] Horizontal line at “Nächste Veranstaltung” header should have max width as on other pages.

Thanks!

**Comment by nosy79** [comment]
Added you to maintainers again. Hope to have some time to write down the publishing process soon.

**Comment by nosy79** [comment]
I really like the checkbox stuff in the issue :)

**Comment by nosy79** [comment]
Sorry. I forgot. But on https://codingdavinci.de:8080/events/ there is no more heading and I forgot if this is correct or not.

**Comment by lucypatterson** [comment]
The mock-up is still the same one https://docs.google.com/document/d/1qXqOuNyOI3UWR5pBzsSHRjgwxTBnIj4BFcaOE99qurY/edit#heading=h.c01389bnuh7w (option A). There should be a header, "Nächste Veranstalltungen", with a [picture](https://codingdavinci.de:8080/img/icons/banderole.png) over it.

**Comment by lucypatterson** [comment]
Cool - at this point I think I can ask the GT for Freigabe. But there are still some outstanding issues - please take care of them as soon as you can:
- [x] Heading should read "Nächste Veranstalltungen", not "Nächste Events".
- [ ] Please left align "Berlin | Nord" in 2nd level Navigation to same left margin as 1st level navigation, "News | Events | Daten | Projekte | ..." (i.e. as it was before).
- [ ] Ensure events overview page banners in body for CdV Berlin and CdV Nord maintain same proportions and relative font size & position at different screen widths. The same aplied for the headers on the respective event pages https://codingdavinci.de:8080/events/berlin/ and https://codingdavinci.de:8080/events/nord.

**Comment by nosy79** [comment]
Ensure events overview page banners in body for CdV Berlin and CdV Nord maintain same proportions and relative font size & position at different screen widths. The same aplied for the headers on the respective event pages https://codingdavinci.de:8080/events/berlin/ and https://codingdavinci.de:8080/events/nord.


Actually the banners on the pages for the events are different from the banners on the events overview page. Do you like one of the styles or what should be different?

**Comment by nosy79** [comment]
I am still working on the menu it is not very easy.

**Comment by lucypatterson** [comment]
Please aim for the same relative font size to logo as here: https://codingdavinci.de/events/ - for both CdV Berlin and Nord, both the header banners on the event pages AND the banners on the event overview page. thx

**Comment by nosy79** [comment]
I seem to cannot do it and I dont know where to start. Currently I also see the text going out of the nord banner on the nord page and on the impressum on nord page the images float outside of the blue container.
I guess it does not make sense to write complex code but I cannot think of a simple solution.
Probably Phillip has one.
Please ask someone with css knowledge what to do - if you could discuss with Gründerteam on what would be the best that would be great.

**Comment by lucypatterson** [comment]
Would you be able to ask your friend again?

**Comment by gitstief** [comment]
I am not really happy with the 2nd level menu for the events page. Especially when switching to and from this page from another subpage like Daten or Projekte, the transition is not very smooth, e.g. there is some sort of hysteresis (the Berlin | Nord 2nd level menu lingers while the rest of the page has already switched).

There is no real visual clue to indicate that the „Berlin | Nord”-2nd-level-Menu belongs to the „Events” entry from the 1st-level-menu. Normally, you'd have a common background color or something like tht.

Also, I would have expected some sort of out-of-the-box Javascript-effect for the unfolding of the 2nd level navigation. 

The Events page is vertically too dense, there should be more whitespace inbetween.

It should read „Veranstaltungen” instead of „Verantstaltungen”.

**Comment by nosy79** [comment]
I would have been great to have these comments a bit earlier. The slow switch of the menu is a problem, indeed, I did not notice before. For the visual clue I could not only have the green font for "Events + Berlin" but also something like a grey background or we cpuld solve the problems with javascript.
I would like to know what the rest of the GT thinks to be able to work out a solution that fits for everyone.

**Comment by anjadigis** [comment]
@gitstief: some sort of hysteresis - meinst Du Verzögerung damit? Die gibt es bei mir nicht. Hatte es eben getestet. visual clue = sieht für mich schon so aus - grüne Markierung von CdV Nord oder Berlin im Menü, während ich auf der CdV-Nord News Ebene bin, macht doch klar, auf welchem Event ich bin. unfolding of the 2nd level navigation: gibt's in der Tat nicht; ich kann nicht von zB Daten oder Projekten direkt CdV N oder Berlin ansteuern. Ist schade, aber die Idee war doch, jetzt das Nötigste zu machen, damit Philipp an den Start kann und dann vermute ich, dass wir im Herbst sowieso Geld anfassen müssen, um jemanden mit einer Grundrestrukturierung der CdV-Seite zu beauftragen. Meine 2Cents - Anja

**Comment by gitstief** [comment]
@anjadigis: Ja, ist mir alles bewusst. Ich finde den Fortschritt für 2 Monate Entwicklung nur recht bescheiden und die Umsetzung für einen Techie-Event wie einen Hackathon fast ein wenig peinlich. 

Ich will mich aber dem weiteren Fortschritt nicht in den Weg stellen, frage mich aber schon, warum die vor Wochen ins Auge gefasste Hinzuziehung eines gelernten Webentwicklers nicht stattgefunden hat. Das ist doch auch unfair @nosy79 gegenüber, die den Admin-Job ja spitze macht.

**Comment by lucypatterson** [comment]
@nosy79 Before this goes online one essential change: text on the Nord banner (both events overview page AND Nord event page header) should read "Nord 2016". Thanks
