### ISSUE TITLE
Regional News

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#134]
Project to reflect parallel regional events in the News section (place-holder).

### Landing Page
With more than one event we will need more than one news article teaser on the landing page, and we will need to be able to represent different regional events. As regional news editorial control is independent we can't rely on chronology to determine which articles appear. Solution will involve categories/tags (one for each region). 
Questions:
- how many article teasers will we include?
- how will we define which articles appear? 

### [News Section](https://codingdavinci.de/news/)
With news from different regional events, we would like to filter by region.

**Comment by nosy79** [comment]
I'd suggest the latest news per event on the landing page. It should most likely have different colored buttons before the head line like a blue nord button before the newest nord news.

**Comment by nosy79** [comment]
@lucypatterson Is it time to do something here?

**Comment by lucypatterson** [comment]
hey - no. We're leaving this for now.
