### ISSUE TITLE
Daten section upgrade

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#135]
Basic
- [x] New filter category, "Region", with values, "Berlin" and "Nord".
- [x] New value "2017" for filter category, "Year". (issue #86)

More complex (no visual redesign)
- [ ] Restructure so that the filter works at the level of individual datasets rather than institutions. PROBLEM: Currently, when you apply various category filters, it returns a list of institutions with datasets that match that filter, BUT it doesn't actually apply the filter to the datasets that belong to that institution - selecting an institution returns ALL datasets that belong to that institution. 
- [ ] We need to be able to link to individual datasets.

**Comment by nosy79** [comment]
- [ ] Das richtige lila für die Regionen aussuchen

**Comment by nosy79** [comment]
Dateneingabe via: https://docs.google.com/forms/d/e/1FAIpQLSfj0KBvzRi6qhhUXv66ejcRLzFjZ5J0YleJGiLcskkjLAXC0g/viewform

**Comment by nosy79** [comment]
@lucypatterson I added year and region. Nord will appear automatically once a Nord dataset is there.
The colors are taken from bootstrap css which leaves me with little choices if I stick with the logic.
https://www.w3schools.com/bootstrap/bootstrap_badges_labels.asp
I quite like the blue ;) - what do you think?

Still looking into the problem of how we can link every data set.

**Comment by lucypatterson** [comment]
Very nice! 
_ I also like the blue. Let's keep it.
_ All datasets from 2016 were 'Nord'. Please reclassify them
For the individual datasets issue, please think about a solution... but don't take too much time. I think Philipp has also been put on this task...

**Comment by nosy79** [comment]
Seems like Philipp is the one to take care of the Daten display.
@philippgeisler : adding you to this task.
