### ISSUE TITLE
New Stopper 

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#136]
New stopper banner text in the header inviting potential participants to sign up to the mailing list for updates. Exact text tbd.
Link: http://eepurl.com/cTI-ov

**Comment by lucypatterson** [comment]
ok. After a lot of back and forth between Lars and me, we decided the text should be "Anmeldung für Teilnehmer". Further instructions on the page the link sends you to make it clear what the deal is (this is a mailchimp page that I can edit myself).
Please implement! :)

**Comment by nosy79** [comment]
@lucypatterson: have a look, its in :).

**Comment by lucypatterson** [comment]
sweet! Thanks Marlen.
