### ISSUE TITLE
New blog post

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#137]
Hi Marlen, 
Please upload the following blogpost: 
https://docs.google.com/document/d/1GaVwFA-jVmHN2Z5UTUyBdDvgVccKb-MLalPCmRKO3bw/edit#
As soon as you can manage it without disrupting the restructuring project. 
I'm not sure anymore whether you need html or markdown for the links so I've left it as embedded links in the google doc. Please let me know what format I should best use for future blogposts. 
Thanks!

**Comment by nosy79** [comment]
@lucypatterson: which date should I use for the news article?

**Comment by nosy79** [comment]
markdown would be great.

**Comment by nosy79** [comment]
should the picture for the preview of the article be the first picture?

**Comment by nosy79** [comment]
I have it online in the preview at https://codingdavinci.de:8080/news/2017/06/29/cdv-berlin.html .
Unfortunatelly it does not yet show up on the main page.
@gitstief : do you have an idea on how to bring this to the front page?
I asked Ralph by mail but I am afraid he might be away already since he did not answer the phone.

**Comment by nosy79** [comment]
But I can see the news online on my local computer...

**Comment by lucypatterson** [comment]
Hi Marlen,
- [ ] The date should be the publish date. 
- [ ] Please use the first image as the preview image (it's also fine to just include it at the top of the post without repeating it again inline). The text "In der schon legendären One Minute Madness von Coding da Vinci machen die Kultur- und Gedächtnisinstitutionen Reklame für ihre Datenpräsentation im Anschluss." belongs in the image caption. Full image caption text is: "In der schon legendären One Minute Madness von Coding da Vinci machen die Kultur- und Gedächtnisinstitutionen Reklame für ihre Datenpräsentation im Anschluss. Bild: Coding da Vinci Kick Off von Heiko Marquardt unter CC BY 3.0" as in the google doc.
- [ ] I don't think we need to worry about seeing a Vorshau of the teaser. Everything worked fine for the last blogpost.
- [ ] Please take care of paragraphs and headings.
- [ ] Please take care of the image caption for the second image. It should read "Kick-Off von Coding da Vinci Nord, der Kultur-Hackathon in Hamburg. Bild: Open Knowledge Foundation Deutschland from Deutschland, Coding da Vinci Nord 2016 - Kick-Off in Hamburg (32760433212), CC BY 2.0". Please take care that it is not duplicated in the body text. 
- [ ] For the footnote - I'm happy for you to decide the best format based on what's feasible. eg smaller text (still readable), a superscript asterisk or number, a horizontal line etc 
- [ ] I realise we need a better title. Please change it to "Hacken für das Kulturerbe" - thanks!

**Comment by gitstief** [comment]
I don't have much time to review the situation thoroughly.

What I learned by looking at github, production and staging servers:
1. staging codingdavinci.de:8080 shows the blogpost, it might be necessary to bypass your local (LAN) proxy to see the fresh content. At the moment we appear to not having configured caching on the ZIB server - doing so might prevent proxy caching.
2. The pull request to merge the develop branch into the production was closed by Marlen, so the newest post in https://github.com/codingdavinci/codingdavinci.de/tree/gh-pages/news/_posts is still the blog post from 2017/04/21. So the blog post can't show up on codingdavinci.de. You'd have to reopen the closed pull request or prepare a new one.

Those are my 2cents.

**Comment by nosy79** [comment]
Ok its in :)

**Comment by lucypatterson** [comment]
Hey - sorry to have to reopen... the teaser text is missing from the [news overview page](https://codingdavinci.de/news/). Perhaps a problem with the server?

**Comment by nosy79** [comment]
@zibboehmert hast du eine Idee?

**Comment by zibboehmert** [comment]
Hm, einerseits scheint es die einzige News zu sein, die direkt mit einem Link anfängt, und andererseits arbeiten die Templates unterschiedlich:
- /index.html -> post_big.html: post.content | strip_html | truncatewords:30
- /news/index.html -> post_normal.html: post.excerpt | strip_html | truncatewords:30

Könnte also am Umgang von post.excerpt mit Links direkt am Anfang liegen...

**Comment by nosy79** [comment]
@zibboehmert : Vielen Dank für diesen interessanten Hinweis. Am Ende war es eine Leerzeile zu viel oberhalb des Post-Beginns, die den Fehler verursachte...

@lucypatterson: bitte guck dir das jetzt mal an. Der Textanfang scheint in der News-Übersicht nicht so richtig gut zu funktionieren.
Lassen wir das so?

**Comment by lucypatterson** [comment]
Looks fine to me in the dev branch. We don't need the 2 Leerzeile before the start of the first paragraph, but as long as it works and the teaser appears it's fine with me.
