### ISSUE TITLE
set shortlink https://codingdavinci.de/berlin

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#146]
Create shortlink:
https://codingdavinci.de/berlin should map to https://codingdavinci.de/events/berlin/
Thanks!

**Comment by nosy79** [comment]
@zibboehmert: Hallo Ralph, gibt es solche Linklisten nicht schon bei euch? Macht das Sinn, sowas dort einzutragen oder soll ich mal versuchen, einen Link ins git zu packen?
Vielen Dank,
Marlen

**Comment by zibboehmert** [comment]
Ich weiß nicht ganz, was ihr mit "shortlink" meint. Was auf meiner Seite (in der Apache-Konfiguration) eingerichtet werden muss, sind Redirects. Da gibt es z.B. schon eine automatische Weiterleitung von /nord nach /events/nord. Soll ich also auch eine von /berlin nach /events/berlin einrichten, oder meint ihr etwas anderes?

**Comment by nosy79** [comment]
@zibboehmert:  Ich glaub so meinte Lucy das. Was ich nicht weiß, ist, ob die Redirects nicht unübersichtlich werden. Ich könnte die auch in einer htaccess im Repo pflegen - was meinst du dazu?

**Comment by zibboehmert** [comment]
Leider muss man dafür in der Server-Konfiguration der htaccess bestimmte Berechtigungen einräumen, die nicht so feingranular sind, dass ich euch nur das Recht auf Redirects geben könnte. Deshalb wäre es besser, wenn ich die Redirects doch direkt in der Apache-Konfiguration aufnehme. Was ich für /berlin auch gerade gemacht habe.

**Comment by nosy79** [comment]
Also ich kann in jekyll offensichtlich eine permalink-Variable im Header von /events/berlin/index.html eintragen und krieg dann den Redirect vom Jekyll hingebastelt. Funktioniert lokal bei mir jedenfalls.

**Comment by zibboehmert** [comment]
Hm, gut, wenn das ohne Änderungen in der Server-Konfiguration und ohne htaccess funktioniert, können wir das gern auch auf Jekyll-Seite machen. Oder funktioniert deine Weiterleitung nur, weil ich es auf dem Server schon eingetragen habe?

Im Staging habe ich die Weiterleitung noch nicht hinzugefügt, kannst da also mal gucken, ob es auch von Jekyll-Seite aus zu machen ist.

**Comment by nosy79** [comment]
Danke :). Leider funktioniert das mit den Permalinks nicht auf der Testseite, von da her belassen wir es einfach beim Apache-Redirect.

**Comment by zibboehmert** [comment]
Gut, so viele Redirects werden es ja wohl auch nicht werden. ;-)

Ich habe den Redirect jetzt auch fürs Staging eingerichtet. Dort gibt es die Unterseite /events/berlin/index.html aber noch gar nicht...

**Comment by nosy79** [comment]
https://codingdavinci.de:8080/events/berlin/ sollte da sein, aber da ist grad 403 permission denied

**Comment by zibboehmert** [comment]
Hm, seltsam. Also nicht das 403, das kommt einfach davon, dass keine Directory Listings erlaubt sind und es keine `index.html` gibt. Die Frage ist, warum gibt es keine `index.html`? Scheint zwei Probleme zu geben:

1. Am 27.06. immer wieder und sonst sporadisch scheint der Webhook nicht durchzukommen! Also sind die Websites nicht auf dem aktuellen Stand. Kennst du die [Liste der Webhook-Calls](https://github.com/codingdavinci/codingdavinci.de/settings/hooks) (und kommst da ran)? Falls mal wieder eine Änderung nicht durchkommen, kann man den Webhook dort nochmal abfeuern. Und wenn es geballt auftritt, kann ich unsere Netzwerkabteilung mit ins Boot holen, damit sie mal auf Netzebene gucken können, ob da bei uns was nicht stimmt. Was bei Einzelfällen immer schlecht zu debuggen ist.

2. Davon unabhängig habe ich die Aktualisierungen mal händisch laufen lassen. `git pull` sagt, alles ist aktuell, und im Jekyll-Verzeichnis liegt unter `/events/berlin` auch eine `index.html`. `jekyll build` läuft ohne Fehler durch, aber trotzdem landet unter `_site/events/berlin` keine `index.html`! Selbst der Verbose-Modus gibt keine weiteren Auskünfte, obwohl die Verarbeitung der Datei dort aufgelistet wird! Leider bin ich kein Jekyll-Profi, vielleicht fragen wir Stefan, ob er da eine Idee hätte?

**Comment by nosy79** [comment]
Auweia...ich hab jetzt nochmal diese Permalink-Variable oben rausgenommen und zack war alles wieder gut...
@lucypatterson ich glaub wir sind fertig...;). Also codingdavinci.de/berlin zeigt jedenfalls auf die richtige Stelle.
