### ISSUE TITLE
Blog post: participant recruitment

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#159]
Hi Marlen,
Could you please upload this blog post: https://docs.google.com/document/d/1GUivdXkWXpG9zX6vGCikwogz9rp2lgfoliemMxwZYag/edit#
I hope all the details will be clear from the document. We're aiming to publish this week Wednesday if possible. It'd be great if you could get it into the staging area for a preview by Wednesday morning.
Thanks!
Lucy

**Comment by nosy79** [comment]
Ok I start :)

**Comment by nosy79** [comment]
@lucypatterson: the news overview page has some issues because of the capital letters. If I take out the "english version" text I only see the h2 heading. I am still on it...

**Comment by nosy79** [comment]
@lucypatterson what do you think of the layout?

**Comment by lucypatterson** [comment]
Hi Marlen,
Cool. I made some layout edits myself (it was easier to do that than try to explain them all here). 
- [x] Please use a larger version of the first image (link to download in the comment)
- [ ] Please include the second image and add image caption style for the caption text
- [ ] Please add all the missing hyperlinks (html).

There is again a problem with the teaser on the news overview page, plresumably because of the line breaks I added. It would be great to be able to keep the line spacing at the top of the article as it is now. The teaser on the landing page seems to handle it fine - I wonder if it might be something easy to fix in the way the teasers are generated - a copy-paste from the landing page teaser to the news overview teaser... What do you think?

**Comment by nosy79** [comment]
@lucypatterson it should be fine now. Btw I fixed the teaser on the news page but it is showing more text now since the images are else too big I felt.

**Comment by lucypatterson** [comment]
Hi Marlen,
The fix for the News overview page is great, though I think you could reduce the teaser length - they're a bit long on mobile. I added quite a few more missing links. 
Last thing to fix is the second image - it's not visible on firefox or chrome.

**Comment by nosy79** [comment]
Oh...ok...added picture...I had a merge conflict due to your edits that probably messed up stuff on my host.
Guess its fine now...

**Comment by nosy79** [comment]
Hey @lucypatterson, I 've put the post online.
