### ISSUE TITLE
More partner logos for Berlin event

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#163]
Hi Marlen,
Please add the following logos to the list of partners on the [Berlin event page](https://codingdavinci.de/events/berlin/), a second row, justified to the centre. Thanks!

![wortmarke_jmb_dt_c0m100y60k15](https://user-images.githubusercontent.com/11370940/29877402-ce8eeb46-8d9f-11e7-8b2b-4c525d8e519b.png)
link to: https://www.jmberlin.de/

![s01_htw_berlin_logo_pos_farbig_cmyk](https://user-images.githubusercontent.com/11370940/29877406-d17d1698-8d9f-11e7-8b2e-b34819bac405.png)
link to: http://www.htw-berlin.de/

Thanks!

**Comment by nosy79** [comment]
merged
