### ISSUE TITLE
Programm section of Berlin event page

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#167]
Hi Marlen,

As promised, here's the text for the Programm section of the [Berlin event page](https://codingdavinci.de/events/berlin/). 
https://docs.google.com/document/d/14o6tZW8JWady2RS0AB-IcTVagnUnaYT7CdDA89LjjRM/edit?ts=59aebbeb#
Please check the [old layout from 2015](https://web.archive.org/web/20150613233840/http://codingdavinci.de/programm/) - we want to create the same layout for this version. Please replace the current content of the "Programm" section with this new content.

I am still confirming the exact titles of the Input sessions, and am trying to prepare pdfs to link to, hopefully I can manage that in the next days. If not we can add them later - minor edits.
Thanks!

**Comment by nosy79** [comment]
@lucypatterson: if every workshop should have a pdf linked to it - do you already have them? It'd be great if you could upload them.

**Comment by lucypatterson** [comment]
Hi Marlen,
I made a couple of small edits to the text and have uploaded the pdfs in [this folder](https://github.com/codingdavinci/codingdavinci.de/tree/gh-pages/downloads/workshops). Could you link them from the titles of each Input session and merge the changes to the main branch. Thanks!

**Comment by nosy79** [comment]
Hey Lucy,

I can do the merge today. Note that the complete program will then be online :).

**Comment by nosy79** [comment]
ok its online.

**Comment by lucypatterson** [comment]
Hey Marlen,
I'm sorry to have to re-open, but could you update all the pdfs with these files: https://drive.google.com/drive/u/0/folders/0B156FtSBxGt-TEFLOXF6R2Jha3M - formatting changes and a couple of typos.
Thanks!

**Comment by nosy79** [comment]
ok its in

**Comment by nosy79** [comment]
@lucypatterson I put it on the production already but I am not sure if it is really in because there was trouble with the transfer. If you still remember one thing you changed it'd be great if you could check for me.

**Comment by lucypatterson** [comment]
looks great :) thanks
