### ISSUE TITLE
Blog Post: new data

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#172]
Hi Marlen,
Here's the details for the blog post we'd like to publish when we publish the data (both on Monday all being well). It'd be great if you could get it up online by Sunday so that we have time for a quick check. Thanks!

Text:
https://docs.google.com/document/d/1RDNo0lpPDDyD5zcr9cQRdBGW8-FDoVJrA3T8iZFKs84/edit#

Image:
![heinrich zille_markt auf dem friedrich karl platz](https://user-images.githubusercontent.com/11370940/30499385-968e9a9e-9a5a-11e7-9f96-266adcc01b81.jpg)

**Comment by nosy79** [comment]
@lucypatterson : already done :). Great you did use markdown - it makes it so much faster to bring it online.
It took 15 min.
Just changed the date to 15.9. because otherwise we wont see the preview - i can change it when you think the post is ok.

**Comment by lucypatterson** [comment]
Hi Marlen,
Looks good, except that the links in the image caption didn't convert to html. Could you take care of it? We'll still publish on Monday as soon as the datasets are ready to go online. Thanks :)

**Comment by nosy79** [comment]
everything fine here?
