### ISSUE TITLE
new partner logo

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#188]
Hi Marlen,
Please can you add the logo for the Naturkundemuseum to the collection on the codingdavinci.de/berlin event page, under "Partners". Thanks!

Here's the image file: https://drive.google.com/file/d/0B156FtSBxGt-ME5Na3oxLU90X2c/view?usp=sharing
Please link to https://www.naturkundemuseum.berlin

**Comment by nosy79** [comment]
@lucypatterson please check :) requesting preview

**Comment by lucypatterson** [comment]
it needs to go under Partner, not Unterstützer - please move it. Thx.

**Comment by nosy79** [comment]
@lucypatterson: Freigabe?

**Comment by lucypatterson** [comment]
Do you think you could put a bit more padding between them, especially the second row. It should look like a grid. Most corporate design rules require a decent amount of empty white space around their logo.
Thanks

**Comment by lucypatterson** [comment]
@nosy79 sorry - almost... please make the MfN logo a little smaller, then we should be good. Thx

**Comment by lucypatterson** [comment]
Hi @nosy79 - I'm so sorry... you were right. The MfN logo should appear under "Unterstützer". It would be great if you could move it - thanks!

**Comment by nosy79** [comment]
@lucypatterson history with github made it easy - please check the current version - Freigabe?

**Comment by lucypatterson** [comment]
@nosy79 if you can use the history to move it back, can you also use the history to make the htw and jmb logos smaller again? They look a little out of proportion. 
MfN logo is fine though. Thanks
