### ISSUE TITLE
Add Datenpräsentationen to 2017 datasets

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#201]
Hi Marlen,

We need to add the Datenpräsentationen from the weekend to the listings of the 2017 datasets on the website. If there's any chance you can manage this by the end of tomorrow that would be amazing. If that's too short notice, please let me know.

They are all listed here: https://docs.google.com/spreadsheets/d/1uElRJI6NikwTjShrGdpz8Pv5MpoVGzs2mH-naqgsO4Y/edit#gid=0
- Where it is a pdf, please download from gdrive, upload to github, and make a link behind the text "Datenpräsentation 2017" from the respective dataset presentation. E.g. as here (scroll to bottom): https://codingdavinci.de/daten/#computerspielemuseum, plus the year.
- If it's a link to a prezi.com presentation, please also write "Datenpräsentation 2017" and link to it - there are 2 of those.
- If there is already a presentation there (because the dataset was presented in a previous year), please keep it, add the year it was uploaded to the linked text, and add the new presentation underneath as "Datenpräsentation 2017".
- We're trying to track down the missing presentations. There should eventually be one for each of this year's 31 datasets.

Thanks!
Lucy

**Comment by nosy79** [comment]
Hey @lucypatterson ,

I guess you will have it on Wednesday morning. Did I understand correctly that every dataset presentation should be a link in "daten"?

Cheers
 	Marlen

**Comment by lucypatterson** [comment]
Yes - I'm talking about codingdavinci.de/daten - links behind the text "Datenpräsentation 2017" at the bottom of the links list for each dataset. 
Wednesday morning will be fine. Thanks :)

**Comment by nosy79** [comment]
Hey @lucypatterson 
requesting Freigabe :)

**Comment by lucypatterson** [comment]
yup - go ahead :)
THanks

**Comment by lucypatterson** [comment]
Hey Marlen,
We got the last dataset presentations from MfN - they're all in the google sheet linked above. Would be great if you could add them. THx!

**Comment by nosy79** [comment]
@lucypatterson ^^

**Comment by lucypatterson** [comment]
thank you! please merge.
