### ISSUE TITLE
add Jury section to codingdavinci.de/berlin

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#202]
Hi Marlen,

Another new section for the Berlin event page – "Jury". Should appear after “Challenges” and before “Veranstalter”. 

Here's the brief:
https://docs.google.com/document/d/1G1VUrn7xE4Ku8LFOiWkcTvHL7J11hrWUSe1EUnwi6u0/edit#heading=h.9nsrgt45hn5a

And here are the images:
https://drive.google.com/drive/folders/0B156FtSBxGt-VHFfVEI1ZDZlVWc

This is not very urgent, but it would be great if you could do it within the next week.
Thanks!

**Comment by lucypatterson** [comment]
Hi @nosy79,
Are there any problems here I should be helping with? Would be good to get it online soon.
Thanks
Lucy

**Comment by lucypatterson** [comment]
Hi @nosy79 - this is getting urgent. Is there a problem?
Thanks
Lucy

**Comment by nosy79** [comment]
Hey @lucypatterson sorry I was on holidays - I'll do now and hope for your review in an hour or so.

**Comment by nosy79** [comment]
@lucypatterson I feel a bit  lost - can you please upload the photo of Thorsten Koch into the image folder, too?

**Comment by lucypatterson** [comment]
he's here already: https://github.com/codingdavinci/codingdavinci.de/blob/gh-pages/img/jury/koch.jpg

**Comment by lucypatterson** [comment]
website Thorsten Koch: http://www.zib.de/members/koch
You're right about Helene's bio. Please shorten to "Projektleiterin (und Coding da Vinci Mitbegründerin)"

**Comment by lucypatterson** [comment]
Hi @nosy79 - approved - please merge :)
