### ISSUE TITLE
2 new blog posts

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#204]
Hi Marlen,

As per request, can you please convert these 2 blog posts and put them up on our website. If you need further information it'd probably be best to ask @fischerdata  / @anjadigis directly. Thanks!

"dear lucy,
bitte stelle den artikel von anja und von mir auf die website
https://blog.wikimedia.de/2017/10/23/die-alten-wissen-es-nicht-immer-besser-oder-coding-da-vinci/
https://www.servicestelle-digitalisierung.de/toller-kick-off-von-coding-da-vinci-an-der-htw-berlin/
den von anja so, dass er zu oberst steht, da allgemeiner. zusammen ergänzen sie sich gut.
merci
Barbara Fischer"

**Comment by nosy79** [comment]
@anjadigis @fischerdata welches Vorschaubild und welchen Autor soll ich für die News jeweils eintragen?
Das Veröffentlichungsdatum nehm ich dann aus dem Blogpost?

**Comment by lucypatterson** [comment]
thanks Marlen!
Lucy
