### ISSUE TITLE
new blog post - register for the Preisverleihung 

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#216]
Hi @nosy79,

Working on a new blog post to announce the opening of registration for the Preisverleihung. Could you please put this in up in dev branch. The text is written by Barbara so already approved. Deadline is asap (sorry).
https://docs.google.com/document/d/1REsK9B74NLoZbE8xbADzl_mqGsHlIrtIExTcUK-8LJU/edit
I'll work on an image and image caption and get them to you as soon as I can. 

Thanks
Lucy

**Comment by lucypatterson** [comment]
Here's the image:
![cdv_graphicrecording](https://user-images.githubusercontent.com/11370940/32632479-1a6fa6d6-c5a4-11e7-9e33-7425a68524ad.png)
Caption: "Coding da Vinci Berlin 2017: Datensets und Pitches. CC-BY Christoph Baierlipp"

thanks!

**Comment by nosy79** [comment]
@fischerdata kann ich die News so online stellen? Die Vorschau befindet sich unter:
http://codingdavinci.de:8080

**Comment by fischerdata** [comment]
Hi Marlen,

danke kann freigeschaltet werden, allerdings ist noch zwei kleiner Fehler
in rot die Korrektur  lg bfisch


   - Out of competition
   - Everybody’s darling

Innovative Entwickler/innen, Designer/innen, Hardware-Bastlern,
Künstler/innen und technikaffinen Kulturbegeisterten haben 6 Wochen lang
hart gearbeitet. Getragen allein von ihrem Wunsch aus *dem* digitalisierten
Kulturgut Berlins und Umgebung neue Projekte zu schaffen. Vielleicht reisen
Sie mit uns mit 80 historischen Fahrkarten um die Welt in einem neuen
Onlinespiel <https://hackdash.org/projects/59eedf7887d0970a0e0a3d1d>. [KEIN
ABSATZ]

Oder prüfen Sie wieviel Spaß es macht,

Barbara Fischer
Kuratorin für Kulturpartnerschaften
via Twitter: @fischerdata

Wikimedia Deutschland e.V. | Tempelhofer Ufer 23-24 | 10963 Berlin
Tel. (030) 219 158 26-(0)44

http://wikimedia.de

Wikimedia Deutschland - Gesellschaft zur Förderung Freien Wissens e.V.
Eingetragen im Vereinsregister des Amtsgerichts Berlin-Charlottenburg unter
der Nummer 23855 B. Als gemeinnützig anerkannt durch das Finanzamt für
Körperschaften I Berlin, Steuernummer 27/681/51985.

2017-11-10 15:11 GMT+01:00 nosy79 <notifications@github.com>:

**Comment by anjadigis** [comment]
@nosy79 Ich gebe frei in Abesenheit von BF; bitte noch Unterschrift des Fotos anpassen: Coding da Vinci Berlin 2017: Datensets und Pitches. Fotograf: Wladimir Raizberg; Graphic Recording: Christoph Baierlipp CC-BY 4.0 - danach kann es online! Danke Dir :)

**Comment by anjadigis** [comment]
@nosy79 @fischerdata OK, nun haben wir beide draufgeschaut.... umso besser. Barbara, ich hoffe die Lizenz ist korrekt.

**Comment by nosy79** [comment]
@fischerdata @lucypatterson  ok I will publish for now :)
