### ISSUE TITLE
Anchor tags for all headers codingdavinci.de/berlin

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#218]
Hi @nosy79,
We have a request for anchor tags/ids  to all the headers on [this page](https://codingdavinci.de/events/berlin/)… (eg [challenges](https://codingdavinci.de/events/berlin/#challenges)). Please name them all something sensible and mail me the list. It's medium-urgent (within the next 3-4 days) :) Thanks!

**Comment by nosy79** [comment]
@lucypatterson sorry I dont really understand what I should do. You can access the Jury with
https://codingdavinci.de/events/berlin/#jury
Is this what you mean? Shall I send you the key words?

**Comment by lucypatterson** [comment]
Ah. If all headings already have ids then please just send the keywords. I had a quick look and it seemed as though some were missing - eg Programm.

**Comment by nosy79** [comment]
Hey Lucy,
here are the current keywords. You can find them in the html - the corresponding line is something like
events<div id="jury" class="container">
above the h2. 

infos-datengeber
infos-teilnehmer
programm
challenges
jury
hosts
partner
unterstützer

**Comment by nosy79** [comment]
done
