### ISSUE TITLE
New section on codingdavinci.de/berlin – Preise

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/codingdavinci.de#219]
Hi @nosy79,

One more new section on https://codingdavinci.de/berlin, "Preise", to be positioned between Programm and Jury. With the same Pokal icon above the heading as previously. Further details here:
https://docs.google.com/document/d/1n9tNbkWsBGtDu7jT2Xr-taWD8EUulgcOOs67dBtaKyw/edit#

It would be great if you could do this in the next days, latest by the end of the week.
Thanks!
Lucy

**Comment by nosy79** [comment]
Hi @lucypatterson , 
can you please point me to the graphics?

Thanks!
nosy

**Comment by lucypatterson** [comment]
I checked the path from internet archive. They're here: https://github.com/codingdavinci/codingdavinci.de/tree/gh-pages/img/preise

**Comment by nosy79** [comment]
@lucypatterson great, thanks :)

**Comment by nosy79** [comment]
Ok its online :) the URL is https://codingdavinci.de/events/berlin/#preise .

**Comment by lucypatterson** [comment]
@nosy79 thank you!
