### ISSUE TITLE
Reisefotografie - Oswald Lübeck & Franz Grasser - auch WWII

### ISSUE THREAD

**Issue by mprove** [codingdavinci/codingdavinci.de#542]
Ein Datensatz der SLUB Dresden[1] wird als Reisefotografie angekündigt. Da allerdings ca. 30% der Fotos Wehrmachtsbilder von Franz Grasser in den Niederlanden und von der Ostfront sind, ist der Titel "Reisefotografie" höchst bedenklich. 

[1] https://codingdavinci.de/daten/#slub-dresden

**Comment by gitstief** [comment]
Vielen Dank @mprove fürs Erinnern. Wir hatten das ja schon vor geraumer Zeit via Twitter-DM besprochen. Ist bei mir leider liegengeblieben.

**Comment by gitstief** [comment]
Ich habe heute (12.07.2019) endlich daran gedacht, die Kollegin bei der SLUB Dresden anzumailen.

**Comment by mprove** [comment]
Und/oder: man könnte den Umstand auch auf den CdV-Seiten anmerken. Für HAPAG Ahoi! habe ich das auch gemacht: "Ein nicht unerheblicher Teil der erhaltenen Fotos stammen aus Grassers Zeit als Soldat in der Wehrmacht. Im Frühjahr 1942 wurde Grasser eingezogen und zunächst in Holland stationiert. Um 1943 kam er in die Ukraine, am 13. November 1944 starb Grasser als Kriegsgefangener in Noworossijsk. Dieser Teil der Sammlung wurde für das Projekt HAPAG Ahoi! weggelassen."
https://mprove.de/chronolab/world/hapag/log.html

Davon abgesehen würde ich mir aber einen erneuten Transfer der LIDO-XML-Daten nach CdV wünschen, denn so einige Infos sind seither von mir und anderen der SLUB mitgeteilt worden und dann auch wieder in deren Metadaten eingeflossen.

**Comment by mprove** [comment]
fixed and ok
