### ISSUE TITLE
Zentral- und Landesbibliothek Berlin > 404 für Bildersuche

### ISSUE THREAD

**Issue by mprove** [codingdavinci/codingdavinci.de#564]
Der Bilder-Link der Zentral- und Landesbibliothek Berlin für die Adressbucheinträge des Jüdischen Adressbuchs von Groß-Berlin von 1931 liefert keine Ergebnisse.

https://codingdavinci.de/daten/#zentral-und-landesbibliothek-berlin 
https://digital.zlb.de/viewer/metadata/1931001_1931/38/
>>
Home  Error
type: recordNotFound
Record not found
No record with the identifier '1931001_1931' found. Please check your input.https://codingdavinci.de/daten/

**Comment by gitstief** [comment]
Damit Du weiterrecherchieren kannst:
https://digital.zlb.de/viewer/image/34039536_1931_1932/1/
ist auch nach wie vor unter dem URN 
`urn:nbn:de:kobv:109-1-2414417`  zu finden, den sollten wir mit dem korrekten Link beim Datenset auf codingdavinci.de ergänzen. Ich gebe das mal vertrauensvoll in die Hände von @ikyriazi.

**Comment by ikyriazi** [comment]
Der Link wurde aktualisiert.
