### ISSUE TITLE
Dortmund Data: download error for Gemälde.xslx 

### ISSUE THREAD

**Issue by mprove** [codingdavinci/codingdavinci.de#588]
The file Gemälde.xslx cannot be downloaded at
http://download.codingdavinci.de/index.php/s/afR79AetzMizk6P?path=%2FMKK%20Gem%C3%A4lde

Error
   cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by ikyriazi** [comment]
Thank you for your contact! The problem should be now fixed.

**Comment by mprove** [comment]
The file can be downloaded at the •••-menu √ 
But it cannot be clicked to display inside the browser. This throws the error.

BTW Clicking a tif files prompts a direct download. 
FYI Firefox and Safari for Mac.
