### ISSUE TITLE
Stopper auswechseln

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#64]

**Comment by lucypatterson** [comment]
CdV Nord call-to-action banner in header will be replaced with a new banner, "AKTUELLES" or "NEWS", hyperlinked to the News section below.

- Lucy will create the banner

**Freigabeprozess Website**
Thu 13.04.17 - Marlen to implement in preview (2 days)
Mon 17.04.17 - Freigabe Gründungsteam (2 days)
Wed 19.04.17 - Marlen to implement (2 days)

**Comment by lucypatterson** [comment]
The reason for including this "Aktuelles" banner is that it seems users less familiar with scrolling sites do not intuitively scroll down to find the rest of the page contents. The new banner would therefore be there only to support the existing navigation, rather than provide any new information or options. 

Possible alternatives:
- Insert a link "a class="smooth-scroll scroll-hint" href="#inhalt"" behind the "Coding da Vinci" logo so that when clicked the page automatically scrolls down (as for the arrows beneath).
- increase the size of the arrows

eg.
![screen shot 2017-04-07 at 15 52 57](https://cloud.githubusercontent.com/assets/11370940/24803111/787b2916-1baa-11e7-8d87-63d32010908f.png)

...to be discussed

**Comment by gitstief** [comment]
Actually, the "Aktuelles" banner was used to present a quick link to the most recent action/news relevant for (potential) participants or people interested in the results of CdV. In 2014 and 2015 we used to link to the registration form for signing up for the Auftaktwochenende or the Preisverleihung. Also the call for data was triggered from there, if I remember correctly.

Some of the links went not to subpages of codingdavinci.de, but to event registration management sites (2014/15: a simple Google Form, 2016: Eventbrite).

A look into the wayback machine helps ...

[28 March 2014](https://web.archive.org/web/20140328221907/http://codingdavinci.de/):
<img width="1062" alt="bildschirmfoto 2017-04-08 um 18 54 58" src="https://cloud.githubusercontent.com/assets/133343/24830794/0fd468bc-1c8d-11e7-88f3-94545c87c0f5.png">

[27 June 2014](https://web.archive.org/web/20140627201604/http://codingdavinci.de/):
<img width="1089" alt="bildschirmfoto 2017-04-08 um 18 57 44" src="https://cloud.githubusercontent.com/assets/133343/24830811/4b6a553a-1c8d-11e7-99da-7cc810d04fb5.png">

[17 July 2014](https://web.archive.org/web/20140717040237/http://codingdavinci.de/):
<img width="1111" alt="bildschirmfoto 2017-04-08 um 18 59 30" src="https://cloud.githubusercontent.com/assets/133343/24830828/87a502e8-1c8d-11e7-9bd6-84048274aaa9.png">

**Comment by gitstief** [comment]
IMO we should try to keep the banner, but always fill it with specific news/actions, like we used to. Doubling navigation elements with a generic "news"-Link is bad idea, I'm with @lucypatterson there.

Once we have 2 or more concurrent events, which might happen for the 1st time with CdV nord 2017 and CdV Berlin 2017, things will get trickier. We might need a shared editorial plan to coordinate the banners content roster.

So, we could end up with showing the registration link  for each event only during the 1  or 2 weeks before the actual event  (if only for fairness reasons).

**Comment by Lars2i** [comment]
Mmh. Mir fällt auch nix besseres ein gerade. Vielleicht

"Jetzt für Berlin anmelden"

**Comment by anjadigis** [comment]
Wäre für mich OK

**Comment by lucypatterson** [comment]
Unfortunately that won't work - there is no way to register as a participant yet. It has to be something along the lines of "Informiere dich...", but also including "Berlin" and "2017". Coudl it be a "save-the-date"? - @fischerdata

**Comment by fischerdata** [comment]
Wie gestern gesagt: man kann uns über twitter folgen, den rss feed abonnieren. Solange wir keine konzedierte Kommunikationsdramaturgie haben bin ich gegen "Wildwuchs". Call for action button kann sein RSS feed abo.

**Comment by lucypatterson** [comment]
Hi @fischerdata @Lars2i.
We need some text for this call-to-action banner in the landing page header. It should be a nice imperitive command that mentions 'Berlin' and '2017', likely split over 2 lines, with a link behind it. A few suggestions from me..
- "2017 WIEDER IN BERLIN!" [link: news article]
- "SAVE-THE-DATE BERLIN 2017" [link: news article]
- "BERLIN 2017 BLEIB INFORMIERT" [link: blog abonnieren]

I'm sure you both would do much better :)
Thanks!

**Comment by Lars2i** [comment]
"2017 BERLIN - SAVE THE DATE" [link: news article] 

wäre mein Vorschlag.

**Comment by fischerdata** [comment]
ich bin für "2017 BERLIN - SAVE THE DATE" [link: news article]

**Comment by lucypatterson** [comment]
@nosy79 - let's implement this and see how it looks in the Vorschau. Looks like it's a link class called
"a.main-signup". I don't think we need the "-", but a line breaks between "BERLIN" and "SAVE" would be good.
The link behind it should be https://codingdavinci.de/news/2017/04/15/cdv-berlin-2017.html
Thx!

**Comment by nosy79** [comment]
Ist drin :)
