### ISSUE TITLE
Scrolling down: "Coding da Vinci" - Text-Redaktion

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#66]

**Comment by lucypatterson** [comment]
Update existing text

- Lars to write

**Freigabeprozess (max 2 weeks - could be shorter)**
Fri 07.04.17- Freigabe BF (2 days)
Tue 11.04.17 - Freigabe Gründungsteam (2 days)
Thu 13.04.17 - Marlen to implement in preview (2 days)
Mon 17.04.17 - Freigabe Gründungsteam (2 days)
Wed 19.04.17 - Marlen to implement (2 days)

**Comment by Lars2i** [comment]
Done. Check the Google Drive: https://drive.google.com/drive/folders/0B156FtSBxGt-c3hac1NtVTNDc2c

**Comment by lucypatterson** [comment]
Requesting Freigabe#1 from @fischerdata: https://docs.google.com/document/d/1F4ESV_a5g8QXbl20a4uJVNLACN7YElowkAoHVWqwHkc/edit

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting Freigabe#2 from the rest of the GT.
Thanks!

**Comment by fischerdata** [comment]
Hi Lucy und Lars,

nach der umfassenden Kritik von Stephan, denke ich, sollte der Text völlig neu geschrieben werden. Noch mal dieser Text soll erklären was Coding da Vinci ist: a) ein Hackathon mit offenen Kulturdaten bei dem GLAMs & Coder zusammenarbeiten. b) Dreiklang Kick-Off-Sprint & Award ceremony c) daten und projekte verwenden freie lizenzen d) jedes Projekt verwendet min 1 datensatz von Coding da Vinci.

**Comment by Lars2i** [comment]
Hi, 
ok. Der Text ist jetzt komplett überarbeitet. Schaut mal bitte rein. Es gibt ein paar Bemerkungen/Fragen zu Verlinkungen. https://docs.google.com/document/d/1F4ESV_a5g8QXbl20a4uJVNLACN7YElowkAoHVWqwHkc/edit 

(Ich will nochmal bemerken, dass der von Stefan zurecht völlig zerpflückte Text nicht von mir stammte, sondern im Moment genau so auf der Website steht. Um unser Arbeitsvolumen schlank zu halten und also nicht ungeprüfte Texte als Ersatz für bereits geprüfte vorzuschlagen, hatte ich deswegen nicht viel dran gemacht.

**Comment by lucypatterson** [comment]
@Lars2i has addressed all of @gitstief's comments. I think it makes sense to run this past the GT again, so... 
Requesting Freigabe from @fischerdata and @anjadigis: https://docs.google.com/document/d/1F4ESV_a5g8QXbl20a4uJVNLACN7YElowkAoHVWqwHkc/edit

Please notify me in a comment when you have finished reviewing.
Thanks!

**Comment by lucypatterson** [comment]
Freigabe from @fischerdata is through with minor edits (small change to last sentence now that CdV Hamburg has confirmed for 2017, added the word "Kulturhackathon" to first sentence in order to define the concept of "hacking")

Requesting final Freigabe from @gitstief and @anjadigis - Thanks!

**Comment by anjadigis** [comment]
@lucypatterson ein kleiner Änderungsvorschlag im vorletzten Satz - ansonsten OK

**Comment by nosy79** [comment]
@lucypatterson ist drin :) ich packs mal in die Vorschau.

**Comment by lucypatterson** [comment]
Requesting Freigabe from @fischerdata 
Thanks!

**Comment by nosy79** [comment]
@fischerdata @lucypatterson  Das neue About: ist in der Vorschau verfügbar

**Comment by fischerdata** [comment]
Gramatikfehler in der Bildunterschrift. Es muss heißen : "vom Coding da Vinci Berlin Team".

**Comment by fischerdata** [comment]
bitte ergänzen: Hardware-Bastler/innen

**Comment by fischerdata** [comment]
bitte ergänzen: Vertreter/innen

**Comment by fischerdata** [comment]
bitte ergänzen: 2017 kehren wir zunächst nach Berlin zurück und

**Comment by fischerdata** [comment]
Bit OHNE Bindestrich: Ethnologischen Museum

**Comment by fischerdata** [comment]
bitte ergänzen: Hardware-Bastler/innen

**Comment by fischerdata** [comment]
sorry for mixing up the tickets. Above comments aim for the blogpost under "aktuelles" ( #70). The Text for #66 is okay no changes needed.

**Comment by lucypatterson** [comment]
cool! Merge! :)

**Comment by lucypatterson** [comment]
Just spotted - can we replace the link behind "Sounds" with this: https://codingdavinci.de/daten/#tierstimmen
Thanks!

**Comment by nosy79** [comment]
Ich habs in die Vorschau gepackt.

**Comment by lucypatterson** [comment]
Danke! Bitte mergen.
