### ISSUE TITLE
Coding da Vinci DNA Text neu ein einfügen

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#67]

**Comment by lucypatterson** [comment]
@gitstief hi! I assume this means a German about/mission-style text here: https://codingdavinci.de/english-infos/ - In our discussion yesterday we discussed implementing it under 'Über uns'. Happy to hear your comments.

**Comment by gitstief** [comment]
Re-Hi @lucypatterson! Yes, that's what I make of this item, too (I have simply copied it from @fischerdata s Googlesheet.) It's should not be a direct back-translation from the english text, because the english text reflects the state of 2014. Since then we went through our strategy process and have formulated our "theory of change" which is quoted in the Code of Conduct, for instance. @fischerdata should be able to point you in the right direction.

Originally, we had this "DNA" on the front page. But, the front page is too long as it is. So, I am fine with putting this mission/vison stuff elsewhere. 

Am not sure, if "Über uns" is the right place/name. As a user, I'd expect info about the organization(s) and people behind CdV when I encounter "about us". Maybe we need another tab "Über Coding da Vinci" (or just rename it).

**Comment by lucypatterson** [comment]
Looking back through the repository and web.archive.org there doesn't seem to have been a stand-alone German version of this text, as thought. There are however a few other former pages that are useful for reference:
- https://web.archive.org/web/20140701051820/http://codingdavinci.de/faq/
- https://web.archive.org/web/20150314201728/http://codingdavinci.de/mitmachen/

**Comment by Lars2i** [comment]
Hi. Wo stehen wir mit dem DNA-Text? Ich würde das eigentlich gern heute abschließen. Wenn sich der englische Text aber nochmal stark verändert, wird das dann ein bisschen fummelig, die Änderungen auch in die deutsche Version einzupflegen. 

Da die Zeit aber knapp ist, mach ich jetzt mit Übersetzung einfach weiter. Sagt mir aber umgehend bescheid, wenn es zu Änderungen gekommen ist. 

Danke

**Comment by lucypatterson** [comment]
Hey Lars,
Since time is tight it makes sense to combine Redaktion of the English (#104) and German text into the same Freigabeprozess - so it's great that you're working on the translation directly in the same doc.. (https://docs.google.com/document/d/1xbEzJ9deGYaT69iqvgu3tUTtwsDohjpNigsvEWWmSSM/edit#) please continue with that. We can work in comments and edits to both versions simultaneously. 

That means we're currently at Freigabe#1 (@fischerdata)
It will then pass to Stephan and Anja for Freigabe#2 - we'll have to push to get through this on Tuesday next week.

**Comment by lucypatterson** [comment]
We will also need to decide where exactly to put this text... Here are a few proposals:
1. "Über uns", before the section about the partners. If necessary, rename the page to "Über Coding da Vinci"
2. New top level navigation page, "Mission", "Unser Mission", "Was ist Coding da Vinci?" etc
3. We bring back the [2nd level navigation previously used on the site (see "Mitmachen" in the navigation bar)](https://web.archive.org/web/20150324000333/http://codingdavinci.de/) and make this a subpage of "Über uns" with the title, "Unser Mission" etc. Could also list "Stimmen" page here...

@fischerdata @anjadigis @gitstief 
Please share your thoughts, thx!

**Comment by fischerdata** [comment]
Hi ihr lieben,

Lucy und ich haben hierzu heute noch gesprochen und befürworten folgende
Lösung: der Englische und Deutsche Text (aka DNA oder eine Art FAQ) bekommt
einen eigenen jedoch zweigeteilten Reiter: "über / about" (ohne Fahne).
Damit wir insgesamt nicht zu viele Reiter haben strukturieren wir
perspektivisch um und reduzieren von 10 auf 9 Reiter:

News | Events | Daten | Projekte | Presse | Dokumentation (hier kämen auch
die Stimmen hin)  | Gründer (vormals "über uns") | über / about (vormals
nur englische Fahne) | twitter (weiterhin nur als Logo)

Sollte dies *nicht bis Donnerstag* umzusetzen sein, dann plädiere ich sehr
dafür den englischen Text und den deutschen Text zunächst einfach
aufeinander folgen zu lassen. Dem englischen Text, der dann der erste
bliebe, würden wir einen Satz voranstellen, "bitte für die deutsche Fassung
bis zum Ende scrollen". Im Mai könnten wir dann in Ruhe an der Struktur
schrauben. Da die Hamburger ja sich entschieden haben, wieder anzutreten
:), müssen wir dann auch die andere Strukturänderung bei Events vornehmen.

Lucy hat hierzu auch das passende issue fortgeführt.


wim bfisch






Barbara Fischer
Kuratorin für Kulturpartnerschaften
via Twitter: @fischerdata

Wikimedia Deutschland e.V. | Tempelhofer Ufer 23-24 | 10963 Berlin
Tel. (030) 219 158 26-(0)44

http://wikimedia.de

Wikimedia Deutschland - Gesellschaft zur Förderung Freien Wissens e.V.
Eingetragen im Vereinsregister des Amtsgerichts Berlin-Charlottenburg unter
der Nummer 23855 B. Als gemeinnützig anerkannt durch das Finanzamt für
Körperschaften I Berlin, Steuernummer 27/681/51985.

2017-04-13 19:21 GMT+02:00 Lucy Patterson <notifications@github.com>:

**Comment by Lars2i** [comment]
@lucypatterson hi lucy. The translation of the DNA is now complete 
https://docs.google.com/document/d/1xbEzJ9deGYaT69iqvgu3tUTtwsDohjpNigsvEWWmSSM/edit#

**Comment by gitstief** [comment]
Der DNA-Text kann so nicht raus. Da ist mir noch zu viel Besserwisserei gegenüber den Kultureinrichtungen drin.

Der Text ist Hintergrundinformation und nicht wichtig, um für CdV Berlin werben zu können. Daher lasst uns bitte die Zeit nehmen, die letzten Ecken und Kanten herauszufeilen.

**Comment by fischerdata** [comment]
Hi Stephan,

der Text ist jetzt von Anja und mir noch einmal überarbeitet worden, ich
denke erst ist deutlich runder und besser geworden. Wir sollten ihn erstmal
online stellen und können dann immer noch weiterfeilen - it's a wiki,
wollte ich schon schreiben ;)

wim bfisch

Barbara Fischer
Kuratorin für Kulturpartnerschaften
via Twitter: @fischerdata

Wikimedia Deutschland e.V. | Tempelhofer Ufer 23-24 | 10963 Berlin
Tel. (030) 219 158 26-(0)44

http://wikimedia.de

Wikimedia Deutschland - Gesellschaft zur Förderung Freien Wissens e.V.
Eingetragen im Vereinsregister des Amtsgerichts Berlin-Charlottenburg unter
der Nummer 23855 B. Als gemeinnützig anerkannt durch das Finanzamt für
Körperschaften I Berlin, Steuernummer 27/681/51985.

Am 19. April 2017 um 22:07 schrieb gitstief <notifications@github.com>:

**Comment by lucypatterson** [comment]
ok! @nosy79 - Here's the final version: https://docs.google.com/document/d/1XcieOI5W34gHrRczxvDs7ek8t9vwUN_m_MJa00ajXek/edit#
Please implement in the Vorschau ("Über").
Thanks!

**Comment by fischerdata** [comment]
ACHTUNG: unter über kommt der ENGLISCHE TEXT. Bitte ausstauschen.

**Comment by nosy79** [comment]
Funny thing is google says its been last edited 3 days ago...

**Comment by nosy79** [comment]
@lucypatterson @fischerdata requesting freigabe - preview: https://codingdavinci.de:8080/about/index-de.html

**Comment by lucypatterson** [comment]
2 small things from me:
- [ ] The last image is missing: https://codingdavinci.de:8080/img/english-infos/projects.jpg. Could you pls add?
- [ ] typo - "Cycberbeetle" should be "Cyberbeetle"

I've also commented these in the google doc: https://docs.google.com/document/d/1XcieOI5W34gHrRczxvDs7ek8t9vwUN_m_MJa00ajXek/edit#

We're expecting @fischerdata to review this text tomorrow morning between 9 and 10am.

**Comment by fischerdata** [comment]
delete: einbringen und damit arbeiten, und >> einbringen, damit arbeiten und

**Comment by fischerdata** [comment]
delete: Kulturinstitutionen in der Regel noch oft verkannt >> Kulturinstitutionen noch oft verkannt

**Comment by fischerdata** [comment]
add link: Das [Projektarchiv von Coding da Vinci] link >> Projekten

**Comment by fischerdata** [comment]
spelling: bundesweitem >> bundesweiten

**Comment by fischerdata** [comment]
delete: erstellt wurden und sollten sie jedem >> erstellt wurden, sollten sie jedem

**Comment by fischerdata** [comment]
commata missing: Quellcode der im Rahmen von Coding da Vinci geschaffenen Anwendungen stehen nach >> Quellcode, der im Rahmen von Coding da Vinci geschaffenen Anwendungen, stehen nach

**Comment by fischerdata** [comment]
change: Hardwareprojekte. Cycberbeetle ist robotischer Nachbau des Chalcosoma-Atlas-Käfers, der heute in einer speziellen High Tech-Insektenbox im Museum für Naturkunde Berlin ausgestellt ist; die Box verfügt über ein eigenes interaktives Heimkino, mit dem der Roboterkäfer von der Natur inspirierte Musikvideos genießt. >> Hardwareprojekte. Der Cycberbeetle ist ein robotischer Nachbau des Chalcosoma-Atlas-Käfers, der heute in einer speziellen High-Tech-Insektenbox im Museum für Naturkunde Berlin ausgestellt ist. Die Box verfügt über ein eigenes interaktives Heimkino, mit dem der Roboterkäfer von der Natur inspirierte Musikvideos genießt.

**Comment by fischerdata** [comment]
done. thanks Lucy, Lars and marlen! Please merge! & send your invoice :) wim bfisch

**Comment by nosy79** [comment]
@lucypatterson ok ich hab die Änderungen alle eingetragen.
