### ISSUE TITLE
Footer Textredaktion

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#68]

**Comment by lucypatterson** [comment]
Footer would be automatically generated, but has to be edited by hand for now. 
**N.B. edits so far are only visible on the landing page!! Can we edit the footer universally?** 
Name of second photographer still missing.

- Lucy to check with BF

**Freigabeprozess**
Wed 19.04.17 - Marlen to implement (2 days)

**Comment by nosy79** [comment]
Do you mean "Kontakt"? If so it seems it is the same on all pages. Please try with another browser since browser caching might trick you.

**Comment by lucypatterson** [comment]
Aah - you're right. Classic browser cache. Sorry for that.

**Comment by lucypatterson** [comment]
wrt Fotos, text should be edited to imply Fotos under CC-BY-SA lizenz oder "freier". Bitte siehe den jeweiligen Bildunterschrift.
Lucy to research correct wording, e.g. https://okfn.de/impressum/
...then we have to gradually work through all the photos and add Quellen.

**Comment by lucypatterson** [comment]
wrt contacts
"Barbara Fischer Projektleitung (siehe auch Koopvertrag) ; Lucy Patterson Projektmanagement. Im Footer sollte dies auch geändert werden." - @fischerdata https://github.com/codingdavinci/codingdavinci.de/issues/101#issuecomment-293236622

So this should be the text...? 

Barbara Fischer
Projekt~~leitung~~koordination Coding da Vinci
Mail: barbara.fischer AT wikimedia.de
Tel: +49 30 289158260 

Lucy Patterson
Projektmanagement Coding da Vinci
Mail: lucy AT codingdavinci.de

(I'd rather not give out my personal number)

**Comment by fischerdata** [comment]
well this could be Schönheitsreparatur sagt man auf Deutsch. muss nicht  zum 21.4. gemacht werden!

**Comment by nosy79** [comment]
@lucypatterson ist deine Adresse noch lucy at codingdavinci.de?

**Comment by nosy79** [comment]
Die Telefonnummer haben Links bekommen. Ich hoffe es gefällt. Probiert es mal mit der Telefon-App.

**Comment by lucypatterson** [comment]
Stimmt. My email address should be lucy.codingdavinci@zib.de. Thanks for spotting that. 
Linked telephone numbers are cool. 😎 
Small edit in the comment above... https://github.com/codingdavinci/codingdavinci.de/issues/68#issuecomment-293275378

**Comment by nosy79** [comment]
Was soll da jetzt eigentlich bei den Lizenzen für die Fotos stehen?

**Comment by lucypatterson** [comment]
I think we agreed to worry about this later. Actually, I don't think the addition of me to the footer is approved..... Let's just leave it as it is for now and come back to it later when all the details are cleared up.
