### ISSUE TITLE
Ausblick 2017

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#70]

**Comment by lucypatterson** [comment]
Save-the-date blogpost (in German) describing planned CdV Berlin 2017: Who, What, Where, When, Why...

- Lars to write
- Lucy image research

**Freigabeprozess (max 2 weeks - could be shorter)**
Fri 07.04.17- Freigabe BF (2 days)
Tue 11.04.17 - Freigabe Gründungsteam (2 days)
Thu 13.04.17 - Marlen to implement in preview (2 days)
Mon 17.04.17 - Freigabe Gründungsteam (2 days)
Wed 19.04.17 - Marlen to implement (2 days)

**Comment by Lars2i** [comment]
Done. Check the Google Drive: https://drive.google.com/drive/folders/0B156FtSBxGt-c3hac1NtVTNDc2c

**Comment by lucypatterson** [comment]
Requesting Freigabe#1 from @fischerdata: https://docs.google.com/document/d/12hyZC0nqLiDxb1aVLtGYSinvu8vxEeqkdQy9ul4xyvg/edit

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting Freigabe#2 from the rest of the GT.
Thanks!

**Comment by fischerdata** [comment]
Freigabe nach kleinen Änderungen im Dokuemnt von mir erfolgt. jetzt bitte vollständig mit dem aktuallen grapgik element in grün und den richtigen daten dem Gründungsteams zur freigabe vorlegen. deadline 19.4. Danke

**Comment by anjadigis** [comment]
von mir bereits jetzt freigegeben mit BF's Änderungen. Hatte den Text schon.

**Comment by lucypatterson** [comment]
Requesting Freigabe#2 from @gitstief (@anjadigis has already approved): https://docs.google.com/document/d/12hyZC0nqLiDxb1aVLtGYSinvu8vxEeqkdQy9ul4xyvg/edit

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting passing to Marlen.
Thanks!

**Comment by anjadigis** [comment]
@lucypatterson außer einer Änderungsbitte sonst einvrestanden.

**Comment by gitstief** [comment]
Ich habe einige kleinere Fehler gefangen und 2-3 Änderungen erbeten.

**Comment by lucypatterson** [comment]
Thanks!
@Lars2i - a couple of minor points to address
(Lars will have time to do this on Thursday)

**Comment by Lars2i** [comment]
Habe die Änderungen durchgesehen und eingearbeitet. Schau mal nach @gitstief, ob es so passt. 

ACHTUNG! Im Newstext steht immer noch "Sie". Auf der Website (#74) aber jetzt "Du". Ist das richtig so?

**Comment by gitstief** [comment]
@Lars2i und ich haben auf dem GoogleDoc diskutiert, letzte Änderungen sind bei ihm in guten Händen. Mein OK ist da.

**Comment by nosy79** [comment]
I need to fill the Author of the news - who would this be? 
I need to fill the date of the news - what should I write - probably 21.4.?
Ah and I need a picture to the post - should I use the timeline or the 2017 Logo or photo?

**Comment by nosy79** [comment]
I will put the blog post in the Vorschau for now.

**Comment by nosy79** [comment]
Not mentioning the author would not be a problem, too.

**Comment by lucypatterson** [comment]
Hi @nosy79,

All good questions. I'll look for a better image (I think a photo from a previous year would be good) and get it to you Tuesday.
I think the date should be 21.04.17 but would like @fischerdata to confirm that. I'd also pass the question of author back to @fischerdata and the GT...

Thanks
Lucy

**Comment by lucypatterson** [comment]
Image suggestions:
<img width="1089" alt="bildschirmfoto 2017-04-08 um 18 57 44" src="https://upload.wikimedia.org/wikipedia/commons/1/11/Coding_da_Vinci_Kick_Off_%2825_%26_26-04-2015%29_044.jpg">
Bild: [Coding Da Vinci Kick Offs 2015](https://commons.wikimedia.org/wiki/File:Coding_da_Vinci_Kick_Off_(25_%26_26-04-2015)_044.jpg), von [Heiko Marquardt](http://www.frischefotos.de/), unter [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/deed.en) 

<img width="1089" alt="bildschirmfoto 2017-04-08 um 18 57 44" src="https://upload.wikimedia.org/wikipedia/commons/e/eb/Coding_da_Vinci_Kick_Off_%2825_%26_26-04-2015%29_070.jpg">
Bild: [Coding Da Vinci Kick Offs 2015](https://commons.wikimedia.org/wiki/File:Coding_da_Vinci_Kick_Off_(25_%26_26-04-2015)_070.jpg), von [Heiko Marquardt](http://www.frischefotos.de/), unter [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/deed.en) 
 
 
<img width="1089" alt="bildschirmfoto 2017-04-08 um 18 57 44" src="https://raw.githubusercontent.com/codingdavinci/codingdavinci.de/gh-pages/img/daten/slub_bibliotheca_gastronomica.jpg">
Bild: Von der Sammlung Bibliotheca Gastronomica, [SLUB Dresden](https://www.slub-dresden.de/startseite/), unter [CC BY SA](https://creativecommons.org/licenses/by-sa/4.0/)
 
 
<img width="1089" alt="bildschirmfoto 2017-04-08 um 18 57 44" src="https://raw.githubusercontent.com/codingdavinci/codingdavinci.de/gh-pages/img/daten/AB05260-edit.jpg">
Bild: Von der Schiffsporträt-Sammlung, [Altonaer Museum](http://www.altonaermuseum.de/de/home), unter [CC BY SA](https://creativecommons.org/licenses/by-sa/4.0/)
 
 
<img width="1089" alt="bildschirmfoto 2017-04-08 um 18 57 44" src="https://raw.githubusercontent.com/codingdavinci/codingdavinci.de/gh-pages/img/daten/MKG-P1994.585-1.jpg">
Bild: ["Turnerin am Barren" von der Sammlung Atelier J. Hamann](https://sammlungonline.mkg-hamburg.de/de/object/Turnerin-am-Barren/P1994.585/mkg-e00131181?s=Atelier+J.+Hamann&h=160), [Museum für Kunst und Gewerbe](http://www.mkg-hamburg.de/en/), unter [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fischerdata** [comment]
publishing date: 21.04.2017
image: first option
and author: Coding da Vinci Berlin Team

**Comment by lucypatterson** [comment]
Hi @nosy79 - please add in this image and caption between the first and second paragraphs:
<img width="1089" alt="bildschirmfoto 2017-04-08 um 18 57 44" src="https://upload.wikimedia.org/wikipedia/commons/1/11/Coding_da_Vinci_Kick_Off_%2825_%26_26-04-2015%29_044.jpg">
Bild: [Coding Da Vinci Kick Offs 2015](https://commons.wikimedia.org/wiki/File:Coding_da_Vinci_Kick_Off_(25_%26_26-04-2015)_044.jpg), von [Heiko Marquardt](http://www.frischefotos.de/), unter [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/deed.en) 

Also as fischerdata says, 
publishing date: 21.04.2017
author: Coding da Vinci Berlin Team
Thx!

**Comment by nosy79** [comment]
@gitstief @lucypatterson  @fischerdata @anjadigis 
Ok, ich hab das Bild eingefügt und den Author geändert. Das Problem ist, dass man vor dem  publishing date die news nicht sieht. Deshalb würde ich es erstmal auf 15.4. lassen für die Vorschau und den 21.4. erst einsetzen, wenn die News abgenommen wurde. Dann kann ich das ändern und die News erscheint erst sichtbar, wenn der 21.4. ist. 
Wäre das so ok?

**Comment by lucypatterson** [comment]
Cool - but could you put the text after the 1st paragraph pls. 

Also, we still need the Bildunterschrift...
Bild: [Coding Da Vinci Kick Offs 2015](https://commons.wikimedia.org/wiki/File:Coding_da_Vinci_Kick_Off_(25_%26_26-04-2015)_044.jpg), von [Heiko Marquardt](http://www.frischefotos.de/), unter [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/deed.en) 

...and it would be great if you could always leave a little white space before the text (i.e. around the image and under the Bildunterschrift) 
Thanks!

**Comment by nosy79** [comment]
Ist drin.

**Comment by lucypatterson** [comment]
Pls see the google doc: https://docs.google.com/document/d/12hyZC0nqLiDxb1aVLtGYSinvu8vxEeqkdQy9ul4xyvg/edit
The second half of the text is missing... please add. There is also a graphic and an image. All other edits are commented in the doc.
Thanks!

**Comment by lucypatterson** [comment]
See ticket #66 for corrections to this text from @fischerdata

**Comment by lucypatterson** [comment]
Hi @nosy79 - I've collected all Barbara's comments for this text together in the google doc: https://docs.google.com/document/d/12hyZC0nqLiDxb1aVLtGYSinvu8vxEeqkdQy9ul4xyvg/edit to give you a better overview. Hope that helps!
Thanks

**Comment by nosy79** [comment]
Yes thank you. Your corrections make it easy to go through and make changes.
Ill put it into the Vorschau.

**Comment by nosy79** [comment]
I should not forget to set the date of the article just before releasing. How can I do this? Probably once it is in merge I should put it back to dev... @lucypatterson better ideas?

**Comment by nosy79** [comment]
Wir haben noch ein kleines Problem im News-Artikel. Da steht jetzt von Team Berlin. Kann das so bleiben oder ist das unschön? Vorschläge wären noch Autor: und Datum: im Newskopf stattdessen.
Ich kann eben leider nicht aus von vom machen, weil sich das dann in allen News ändert.
@gitstief @anjadigis @fischerdata @lucypatterson  Ideen oder Vorlieben?

**Comment by lucypatterson** [comment]
The "von" is an automatic label for the author text field. It imagines the author will always be a named person. 
Alternatives we already discussed include "von:" "Autor:"... I wonder if we could just remove the label all together. But I think it would then be important to signify better that this was metainfo rather than bodytext - perhaps with a different text-style, eg italics...

**Comment by nosy79** [comment]
Gibt es hier irgendetwas neues oder kann das Ticket zugemacht werden?
