### ISSUE TITLE
Strukturveränderung: mehrere Events laufen parallel

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#71]
vgl. Lösung für Projekte nach Jahren, gerne aber mit einem Bild-Button

**Comment by lucypatterson** [comment]
After the meeting yesterday, the plan is to implement two hyperlinked banners in the header section: (left) Coding da Vinci Berlin 2017; (right) Coding da Vinci Nord 2016. On clicking, they will lead to the respective info page.

Potential problem:
- Assume Berlin will be shown by default, but both banners will remain in the header. User might not realise that clicking the CdV Nord banner will lead to further content (general problem with call-to-action banners in the header).

Alternative proposal:
1. make https://codingdavinci.de/events/ into an overview page for multiple events displayed as clickable tiles (upcoming & recent past, potentially also full archive): remove header section (as, for example, https://codingdavinci.de/projekte/).  (for similar layout examples see http://ouisharefest.com/, http://sciencehackday.org/...)
2. Give each regional event their own subpage with own webbanner in header. Implications for navigation... (is a 2nd level navigation possible?)

**Comment by gitstief** [comment]
We must plan for more than CdV Berlin and Hamburg, since CdV Rhein-Main is under way for early 2018. Therefore, definitely go for one of the alternative proposals.

**Comment by lucypatterson** [comment]
@gitstief agree. We will need to discuss this in a dedicated meeting and I definitely have some suggestions for how to go forward. However, the timeline is tight for the 21.04.17 deadline to get some basic updates online. In the meeting yesterday it seemed that we might have to work with an interim solution. I'll be meeting Barbara and Marlen on Monday - we'll discuss it then.

**Comment by lucypatterson** [comment]
@fischerdata @gitstief @anjadigis @nosy79 
Here are 3 suggestions for structures to allow for parallel regional events (I worked through the proposal from the kickoff last week which then inspired some new options): 
https://docs.google.com/document/d/1qXqOuNyOI3UWR5pBzsSHRjgwxTBnIj4BFcaOE99qurY/edit#heading=h.c01389bnuh7w
Please comment and/or propose alternatives. Thanks!

@anjadigis - no, so far I haven't contacted Philipp. Do you think he would have alternative suggestions? 
@fischerdata @gitstief - should I invite Philipp to contribute here?

If we really need more time to reach a decision we could, as an interim solution, just swap in the Berlin 2017 infos in place of the current CdV Nord contents - delaying the parallel-events re-structuring until a later date.

**Comment by gitstief** [comment]
In order to enable Philipp for participating in issue discussions, I believe it's necessary to make him a member (not an owner) of our codingdavinci.de repositorium. But I am not sure, if it doesn't work without explict invitation as a member. @lucypatterson As an owner you can invite Philipp, he is @philippgeisler on github.

I am all for inviting Philipp (Hi, @philippgeisler - Wie geht's, wie steht's? Hintergrund ist, dass wir mit codingdavinci.de von der OKF in ein eigenständiges Organisations-Repo für Codingdavinci umgezogen sind. )

**Comment by nosy79** [comment]
Basically I can do Option A as requested by Lucy via GoogleDocs. I am looking forward to a final wish from the Gründerteam.
What I would also like to know is what would be a minimum requirement for 21st April and what could also be done later.

**Comment by gitstief** [comment]
Let's test if membership is necessary for taking part in issue discussions. @mbuechner: Wärst Du so nett, hier kurz zu antworten, falls Du diesen Kommentar mitbekommst.

**Comment by mbuechner** [comment]
Kurze Antwort. ;-)

**Comment by gitstief** [comment]
(@mbuechner is Michael Büchner, a colleague of mine at DDB and seasoned Coding da Vinic veteran). So, membership isn't necessary, mentioning suffices. Therefore, @philippgeisler should be aware of this discussion.

**Comment by lucypatterson** [comment]
... also, please be aware I am not a web designer. If at all possible it would be great for someone with the relevant expertise to look over this.

We can collect suggestions, but ultimately the Gründungsteam ( @fischerdata @gitstief @anjadigis ) will need to agree how we proceed.

**Comment by fischerdata** [comment]
Please, für den Moment sollten wir uns erst einmal  auf  die Aktualisierung der Website konzentrieren. Wir haben noch kein OK von Hamburg, ob sie tatsächlich  es wuppen werden. Daher die Frage nach diesem Verfahren bitte zurückstellen.

My 2 cent. Lasst uns einen guten Workflow für Coding da Vinci Berlin etablieren, dann geht es weiter auf die nächste Ebene. OK? Vor allem Richtung Stephan.

**Comment by fischerdata** [comment]
Kommentar von nosy79:
nosy
Hey,

also ich warte noch bis ihr damit durch seid. In der Zwischenzeit wäre auch noch die Frage:

wenn ich Variante A einbauen soll und das evtl. zeitlich bis 21.4. nicht klappen sollte, was wäre die Mindestanforderung?
Schlichte Seite mit "Coming soon"?
Ich würde es wirklich gut finden, wenn wir nur an einer Stelle, und zwar in Github Issues, diskutieren.

Dazu: solange es keine Aussage von HH zu CdVNord 2017 gibt, machen wir es im April so wie letztes Jahr  für CdV Nord. Sobald Zusage von CdV Nord vorliegt, bauen wir die Lösung A

wie hier https://docs.google.com/document/d/1qXqOuNyOI3UWR5pBzsSHRjgwxTBnIj4BFcaOE99qurY/edit?disco=AAAABI7UIfI vorgeschlagen. Wir hatten doch schon am 4.4. gesagt, dass zwei aktiv buttons auf einer Seite möglich wären.

**Comment by lucypatterson** [comment]
To clarify...
**Plan A** [Option A](https://docs.google.com/document/d/1qXqOuNyOI3UWR5pBzsSHRjgwxTBnIj4BFcaOE99qurY/edit) (or similar) - IF we have time, and/or IF HH confirms their participation before our 21.04.17 deadline
**Plan B** Simply remove CdV Nord 2016 contents and replace with CdV Berlin 2017 (see mock-up below)

![d_event](https://cloud.githubusercontent.com/assets/11370940/24917331/1d042f34-1edd-11e7-86db-b38d4e25a0c5.png)

Do I understand that correct? No need for 2 buttons in the header.

**Comment by gitstief** [comment]
Dann sollten wir aber aufhören, in diesem Issue weiter zu diskutieren und ein neues Issue mit der Schmalspur-Schnellschuss-Variante B für CdV Berlin anlegen.

Auf diesem Ticket diskutieren wir dann bitte mit ausreichend Zeit noch eine vernünftige Umsetzung, die mehrere Standorte und Jahre berücksichtigt und uns nicht schon übermorgen um die Ohren fliegt. Das ist Option A nämlich auch nicht.

**Comment by nosy79** [comment]
@gitstief @fischerdata @lucypatterson @anjadigis 
ich hab noch einen eigenen Vorschlag mit hineingepackt.

**Comment by nosy79** [comment]
Wir nehmen wohl Variante A...

**Comment by lucypatterson** [comment]
Comments to draft#3. https://github.com/codingdavinci/codingdavinci.de/issues/131

**Comment by lucypatterson** [comment]
Comments to draft#6. #133 
@nosy79 - I need owner status, and/or to be a member of the Berlin team in order to assign this to you... thanks.
