### ISSUE TITLE
Button CdV Berlin

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#72]

**Comment by lucypatterson** [comment]
All graphics files: https://drive.google.com/drive/u/0/folders/0B8GaLtzJXlwdSzVhQkNLeC05MzA 
CD: 
- fonts styles delivered through the CMS: _Archive_ for the section headings (and logo?), and _droid serif_ for everything else
- colours...

**Freigabeprozess Website (max 6 working days - could be shorter)**
Thu 13.04.17 - Marlen to implement in preview (2 days)
Mon 17.04.17 - Freigabe Gründungsteam (2 days)
Wed 19.04.17 - Marlen to implement (2 days)

**Comment by lucypatterson** [comment]
This issue is dependent on decisions of #71

**Comment by lucypatterson** [comment]
If we are going for Plan B, as per https://github.com/codingdavinci/codingdavinci.de/issues/71#issuecomment-293302903, we need a new header banner for the Berlin event to replace this:
![screen shot 2017-04-15 at 14 41 30](https://cloud.githubusercontent.com/assets/11370940/25063614/ad242916-21e9-11e7-8a98-2d81f0b08f0c.png)

I propose the new banner should look like this:
![screen shot 2017-04-15 at 14 37 47](https://cloud.githubusercontent.com/assets/11370940/25063607/81b43712-21e9-11e7-9987-39b52ea0b443.png)
i.e. same as the landing page logo, but white behind the CdV png and with a subheading "BERLIN 2017", 
font-family: "Archive",serif;
font-size: 40pt;

**Comment by nosy79** [comment]
Das Logo ist drin. Ich find es noch nicht so ganz  gelungen. Die Farbe ist ein bisschen anders als auf der Startseite.
Ich würde das Startseiten-Logo nehmen und statt Kultur-Hackathon einfach Berlin 2017 hinschreiben (evtl. in bold). Dafür müsste keine neue Grafik gebaut werden.

**Comment by lucypatterson** [comment]
Hi @nosy79 
Genau meinte ich es :) I didn't mean for you to use the image file... I created the logo posted above using firebug, then took a screenshot. 

Please use the code for the landing page logo, make a white background to the "COD1NG DA V1NC1" logo, and replaced "Der Kultur-Hackathon" with "BERLIN 2017", font-family: "Archive",serif; font-size: 40pt;

Thanks!

**Comment by nosy79** [comment]
Ok - did that :)

**Comment by lucypatterson** [comment]
Pls reduce size of white background a little bit - there are some pixels showing at the bottom of the logo.
Thanks!
