### ISSUE TITLE
Einfügen Ankündigungstext CdV Berlin

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#74]

**Comment by lucypatterson** [comment]
Copyedit something appropriate from CdV Nord 2016 text https://codingdavinci.de/events/
Will need to doublecheck status of partners.
See also https://github.com/codingdavinci/codingdavinci.de/issues/75 

- Lars to write

**Freigabeprozess (max 2 weeks - could be shorter)**
Fri 07.04.17- Freigabe BF (2 days)
Tue 11.04.17 - Freigabe Gründungsteam (2 days)
Thu 13.04.17 - Marlen to implement in preview (2 days)
Mon 17.04.17 - Freigabe Gründungsteam (2 days)
Wed 19.04.17 - Marlen to implement (2 days)

**Comment by Lars2i** [comment]
Done, check the Google Drive: https://drive.google.com/drive/folders/0B156FtSBxGt-c3hac1NtVTNDc2c

**Comment by anjadigis** [comment]
kommentiert, kleine Änderungen

**Comment by lucypatterson** [comment]
Requesting Freigabe#1 from @fischerdata: https://docs.google.com/document/d/1OgyX0Zr8qEygvfNOtwiKmASYo5-RAzXumuo8AHs7m2U/edit

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting Freigabe#2 from the rest of the GT.
Thanks!

**Comment by fischerdata** [comment]
Mit kleinen Änderungen und der bitte bitte einheitlich siezen oder duzen in der Ansprache. Außerdem ist bislang keine Party am 2.12. geplant. Mir ist nicht mehr klar, wo dieser Text jetzt steht:
a) unter news von der landing page
b) unter events regional Berlin 
c) als allgm intro text was ist CdV vgl. Englische Version?

Ich nehme an B, dafür halte ich ihn geeignet.

jetzt bitte aktualisieren und freigeben bis zum 19.4. durch das Gründungsteam.

**Comment by anjadigis** [comment]
mit @fischerdata Änderungen von mir bereits jetzt frei gegeben.

**Comment by lucypatterson** [comment]
Requesting Freigabe#2 from @gitstief (@anjadigis has already approved): https://docs.google.com/document/d/1OgyX0Zr8qEygvfNOtwiKmASYo5-RAzXumuo8AHs7m2U/edit

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting passing to Marlen.
Thanks!

**Comment by gitstief** [comment]
I caught two odd phrasings and offered alternative versions.

Other than that, I like the text and happily give my "Freigabe" ;-)

**Comment by lucypatterson** [comment]
@nosy79 - Logo at top of page as described here: https://github.com/codingdavinci/codingdavinci.de/issues/72#issuecomment-294291173

**Comment by nosy79** [comment]
Just added the changes to the branch 17-4-events. Will merge when ready :).
Should this logo be only visible on the events page or should this logo be generally used for the whole site?

**Comment by lucypatterson** [comment]
Hi @nosy79 

A few corrections based on comparison with http://web.archive.org/web/20160814005440/https://codingdavinci.de/events/:
- [x] Please increase space between h2 titles and body text (as here https://codingdavinci.de/events/)
- [x] Please use green accent colour for "Berlin" in the first h2 heading
- [ ] Please implement the relevant illustrations above all h2 titles, e.g. here:
![screen shot 2017-04-16 at 17 20 26](https://cloud.githubusercontent.com/assets/11370940/25072207/077d7522-22c9-11e7-8724-5f202c3f42ff.png)

The others are:
- Infos für Teilnehmer: haende.png
- Infos für Kulturinstitutionen: buch.png
- Programm: uhr.png

- [ ] Using the timeline graphic is good here (rather than Kasten), but please correct the text (**Kick-Off**
21./22. Oktober, Hochschule für Technik und Wirtschaft | **Sprint** 6 Wochen Zeit, um kooperativ Projekte umzusetzen | **Preisverleihung** 2. Dezember)
- [ ] Under "Programme", the layout of the Kasten text should be as below:
![screen shot 2017-04-16 at 17 40 10](https://cloud.githubusercontent.com/assets/11370940/25072337/c908cd8e-22cb-11e7-9c1c-6690aafd8bf6.png)
- [ ] section "INFOS FÜR KULTURINSTITUTIONEN" - please change the email contact address to codingdavinci@zib.de
- [ ] section "INFOS FÜR KULTURINSTITUTIONEN" We should use "Sie" - please change. 
- [ ] Please implement responsive width for body text as https://codingdavinci.de/events/ (weniger wichtig)

Thanks!
Lucy

**Comment by nosy79** [comment]
Hey Lucy,
I still struggle with some stuff in here but also new questions came while I was struggling:
I can leave some space between h2 and the text. Should I do this for all of the site? Thats how it currently is in the preview.
There are these lines around the h2 text. How wide should this be?
I hope to prepare the layout changes for tomorrow. It might make sense to go through details while we are at the same desk with Barbara.

**Comment by lucypatterson** [comment]
Hey Marlen
> I can leave some space between h2 and the text. Should I do this for all of the site? Thats how it currently is in the preview.

Looks good - I think it would be good to use this everywhere in the site - thanks for implementing that.
> There are these lines around the h2 text. How wide should this be?

That's a good question - looking at the site as it is now there are some inconsistencies. I would suggest we use the responsive solution currently used here: https://codingdavinci.de/about/ and try to be consistent... 
Either (widescreen)
    margin-left: 8.33333%;
    width: 83.3333%;
Or (narrow screen - I can't figure out what the cut-off is...)
    padding-left: 15px;
    padding-right: 15px;
    position: relative;

**Comment by fischerdata** [comment]
@gitstief @lucypatterson @anjadigis @nosy79 
In der Vorschau zu dem Text zu Coding da Vinci Berlin 2017 [  ] wird unter Veranstalter auch die OKF geführt. Ist das korrekt? Aus meiner Sicht ist die OKF Träger des Gesamtevents, aber nicht Veranstalter von Coding da Vinci Berlin. Was meinen die anderen beiden Gründer?
wim bfisch

**Comment by nosy79** [comment]
Die Vorschau dazu befindet sich unter https://codingdavinci.de:8080/events/

**Comment by gitstief** [comment]
Ja, OKF ist und bleibt Gründerin, ist aber nicht Teil des Berliner Veranstalterteams.

LG
Stephan

________________________________
Von: fischerdata [notifications@github.com]
Gesendet: Mittwoch, 19. April 2017 09:01
An: codingdavinci/codingdavinci.de
Cc: Bartholmei, Stephan; Mention
Betreff: [Marketing Mail] Re: [codingdavinci/codingdavinci.de] Einfügen Ankündigungstext CdV Berlin (#74)


@gitstief<https://github.com/gitstief> @lucypatterson<https://github.com/lucypatterson> @anjadigis<https://github.com/anjadigis> @nosy79<https://github.com/nosy79>
In der Vorschau zu dem Text zu Coding da Vinci Berlin 2017 [ ] wird unter Veranstalter auch die OKF geführt. Ist das korrekt? Aus meiner Sicht ist die OKF Träger des Gesamtevents, aber nicht Veranstalter von Coding da Vinci Berlin. Was meinen die anderen beiden Gründer?
wim bfisch

**Comment by anjadigis** [comment]
Genauso, VG, Anja

**Comment by lucypatterson** [comment]
hi @nosy79 - I've edited the complete todo list for this ticket in the comment above: https://github.com/codingdavinci/codingdavinci.de/issues/74#issuecomment-294358382

**Comment by nosy79** [comment]
Ok lets do another preview :)

**Comment by fischerdata** [comment]
bitte Leerzeichen ergänzen:  Wir helfenIhnen gern dabei >> Wir helfen Ihnen gern dabei

**Comment by fischerdata** [comment]
Bitte Satzzeichen korrekt & kürzen: Melden Sie sich einfach. ? Schreiben Sie uns >> Melden Sie sich einfach.

**Comment by fischerdata** [comment]
Bitte satzzeichen korrekt:  abonniere unser Blog.. >>  abonniere unser Blog.

**Comment by fischerdata** [comment]
ready
