### ISSUE TITLE
Ausblick auf den Projektverlauf CdV Berlin

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#75]

**Comment by lucypatterson** [comment]
Not sure of the connection/difference between this and https://github.com/codingdavinci/codingdavinci.de/issues/74. 
Nonetheless, may depend on website structure solution for regional events.

**Comment by gitstief** [comment]
Again, @fischerdata should know. And of course, it's OK to close issues as duplicates. You're the boss!

**Comment by Lars2i** [comment]
Done. Check the Google Drive: https://drive.google.com/drive/folders/0B156FtSBxGt-c3hac1NtVTNDc2c

**Comment by fischerdata** [comment]
please do close open issues!

**Comment by gitstief** [comment]
@fischerdata Na ja, wenn wir als Gründer auf die Texte schauen sollen, dann kann CLOSE erst nach Abnahme erfolgen. Ich warte immer noch auf das GO zum Gegenlesen, nachdem uns @lucypatterson gestern zurückgepfiffen hatte.

**Comment by lucypatterson** [comment]
I'm closing this as a duplicate of #74
