### ISSUE TITLE
Introtext aktualisieren

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#84]

**Comment by lucypatterson** [comment]
https://codingdavinci.de/daten/
Would recommend copyediting to be generally applicable to any CdV event. 

- Lars to write

**Freigabeprozess (max 2 weeks - could be shorter)**
Fri 07.04.17- Freigabe BF (2 days)
Tue 11.04.17 - Freigabe Gründungsteam (2 days)
Thu 13.04.17 - Marlen to implement in preview (2 days)
Mon 17.04.17 - Freigabe Gründungsteam (2 days)
Wed 19.04.17 - Marlen to implement (2 days)

**Comment by Lars2i** [comment]
Done (First draft). Check the Google Drive https://drive.google.com/drive/folders/0B156FtSBxGt-c3hac1NtVTNDc2c

**Comment by lucypatterson** [comment]
Requesting Freigabe#1 from @fischerdata: https://docs.google.com/document/d/1XRUlsj_v0O-K3RDbzN6WwuZ5PqrC_FoHMLxTm9DP43U/edit

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting Freigabe#2 from the rest of the GT.
Thanks!

**Comment by fischerdata** [comment]
works for me. bitte info@codingdavinci de verwenden. **Vorausgesetzt**, dass diese Email irgendwo hinführt. Ansonsten müssen wir es bis es soweit ist bei Barbara.fischer@wikimedia.de belassen. Gilt für alle Stellen!

**Comment by lucypatterson** [comment]
Requesting Freigabe#2 from @gitstief & @anjadigis: https://docs.google.com/document/d/1XRUlsj_v0O-K3RDbzN6WwuZ5PqrC_FoHMLxTm9DP43U/edit

Please notify me in a comment when you have finished reviewing. Lars and I will check and incorporate edits before requesting passing to Marlen.
Thanks!

**Comment by gitstief** [comment]
To avoid confusion with the different GoogleDoc links you could maybe incorporate the corresponding github issue number at the top of the GoogleDoc in question. Or naming Issues and GoogleDocs a like might help, too. Just my 2 cents.

@lucypatterson : Review finished.

**Comment by lucypatterson** [comment]
Thx @gitstief - a few copypaste mistakes - I think I've corrected them now. The issue number is always in the googledoc filename.

**Comment by gitstief** [comment]
m) Of course it is, my bad. Thx for bearing with me @lucypatterson

**Comment by nosy79** [comment]
Hab den Text geändert und stelle ihn direkt in die Vorschau (branch gh-pages-develop)

**Comment by gitstief** [comment]
Ich wäre ja dafür, den Satz

> Auf der Suche nach ergänzenden, offenen Datensets? Hier lang.

mit dem aus codingdavinci.de herausführenden Link einfach zu streichen. Lenkt nur ab und das Googledoc erzeutgt extra Wartungsaufwand.

**Comment by lucypatterson** [comment]
Here's the link to the Vorschau https://codingdavinci.de:8080/daten/
Would be great to get feedback from @fischerdata and @anjadigis also.
Please notify us in a comment when you have finished reviewing.
Thanks!

**Comment by fischerdata** [comment]
Freigabe erfolgt. Vorausgesetzt die Emailadresse info@codingdavinci.de funktioniert schon, sonst lucy...@codingdavinci.de

**Comment by fischerdata** [comment]
Satz "Auf der Suche nach ergänzenden, offenen Datensets? Hier lang." ersatzlos streichen.  merci

**Comment by anjadigis** [comment]
#84 mit Barbaras Änderungen OK @lucypatterson

**Comment by lucypatterson** [comment]
Hi @nosy79 
A couple of small edits to the text... I've marked both with a comment in the doc:
https://docs.google.com/document/d/1XRUlsj_v0O-K3RDbzN6WwuZ5PqrC_FoHMLxTm9DP43U/edit

Thanks!

**Comment by fischerdata** [comment]
Bitte ergänzen: Daten zur kulturellen Bildung beitragen, Kreativität und freies Wissen fördern. >> Daten zur kulturellen Bildung beitragen, sowie Kreativität und freies Wissen fördern.
