### ISSUE TITLE
Pressespiegel CdV Nord 2016

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#94]

**Comment by mprove** [comment]
Hier fehlt noch der NDR Film zum CollecTOURmat

**Comment by gitstief** [comment]
Hier schon einmal notiert:

https://www.ndr.de/fernsehen/sendungen/rund_um_den_michel/Auf-Zeitreise-mit-dem-KollekTOURmat,rundumdenmichel2164.html

**Comment by nosy79** [comment]
Habs übernommen...
